### ISSUE TITLE
The window buttons of the app window appear dim in dark mode

### ISSUE THREAD

**Issue by Cyberdroid1** [digimezzo/dopamine#127]
![image](https://user-images.githubusercontent.com/51435948/124000490-40a78c00-d9f1-11eb-8fb3-223bb340b037.png)

**Comment by digimezzo** [comment]
Preview 4 adds custom theme support. This issue can be addressed by the user by creating a new theme and tweaking the colors.

**Comment by Cyberdroid1** [comment]
Thank you!
