### ISSUE TITLE
Start menu link for Dopamine 3 replaces the link for Dopamine 2

### ISSUE THREAD

**Issue by vivadavid** [digimezzo/dopamine#128]
Hi, Raphaël!

As you said in your blog post, you can certainly have Dopamine 2 and 3 installed separately in the same computer. However, the start menu link for Dopamine 2 gets replaced by the link for Dopamine 3, as they have the same name, so as a result, you can only open Dopamine 3 from the start menu. I've fixed it manually, but to avoid this problem in future releases, you could maybe rename the link as "Dopamine 3" or "Dopamine Preview".

I hope this feedback is useful to you and thank you for your hard work.

**Comment by g-yui** [comment]
I have Dopamine on my tray so I didn't notice this when I installed the preview, nice catch!
Needless to say, I have the same issue ;)

**Comment by digimezzo** [comment]
Hi! Thanks for reporting this. I didn't catch that one. I'll fix it for the next preview.
