### ISSUE TITLE
The beautiful "Now Playing" screen from Dopamine 2 is gone

### ISSUE THREAD

**Issue by neubland** [digimezzo/dopamine#135]
One of the prettiest things about Dopamine 2 was the great Screen where it showed what is currently playing with the cover nice and big and the background was the cover too. This seems to be gone in Dopamine 3. Maybe this is intentional, maybe it is a bug that makes me unable to click it, just wanted to say it was a great feature and it would be great if that feature would be in Dopamine 3 too.

**Comment by digimezzo** [comment]
@neubland It's coming back. This is just a preview, with a lot of missing features. All features of Dopamine2 will be in Dopamine 3.
