### ISSUE TITLE
Same Genre appears multiple times

### ISSUE THREAD

**Issue by neubland** [digimezzo/dopamine#136]
Genres of which there are multiple albums of appear multiple times. For example there are 5 entries "Alternative" for 26 alternative Albums. Some of these albums use a Genre ID-Tag that uses ; as separator (Autechre is "Alternative; Electro" for example). If it would be helpful I can share the affected files.

![image](https://user-images.githubusercontent.com/34939446/124353533-5abab780-dc07-11eb-9800-0c4119fb4704.png)

**Comment by neubland** [comment]
Maybe this is related: The camelcase-Genres "AlternativeElectro" etc. appear in the list but are empty. I assume they are a consequence of handling the ;-separated genres. I am pretty sure there are no actual "AlternativeElectro" genres in my library, just "Alternative; Electro" (which means that these files have 2 Genres)

**Comment by digimezzo** [comment]
@neubland I think I found the issue. Could you attach your Dopamine.db to this issue so I can compare without your situation? Thank you.

**Comment by neubland** [comment]
@digimezzo I'm not sure how to best attach that kind of file as it is not directly supported by github, so I put it on wetransfer: https://we.tl/t-vej2zDoqu7 The link is valid for one week. If I should use another channel to transfer the file I can do so.

**Comment by digimezzo** [comment]
@neubland Thanks a lot for your database. I was able to fix the bug. You'll have the fix soon, in Preview 2.
