### ISSUE TITLE
Long loading times for songs

### ISSUE THREAD

**Issue by MicRaving** [digimezzo/dopamine#137]
The new preview introduces long song loading times for me that didn't exist in the self-compiled version two weeks ago nor Dopamine 2. Now the average song takes around 10 seconds to load. I listen to FLACs that are stored on a network share which is connected via SMB - maybe this is part of the problem.

**Comment by digimezzo** [comment]
@MicRaving There was no FLAC support 2 weeks ago, only MP3. Coudl it be that you loaded MP3's from your network share. MP3's are much smaller than FLACs, that could explain the shorter loading speed.

**Comment by MicRaving** [comment]
Sorry, probably my mistake, then. I thought that it was already implemented two weeks ago but maybe I'm mixing up something with Dopamine 2. Tested the loading times again and they are <1s in Dopamine 2 compared to 8-10s in Dopamine 3. The loading times seem unrelated to the length of the song.

**Comment by digimezzo** [comment]
@MicRaving Thanks for the info. I'll test out loading times on network shares and see what is going on.

**Comment by MicRaving** [comment]
Thank you! Just a small update: The newest source code changes after the preview 1 release reduced the loading times to 2-3s.

**Comment by MicRaving** [comment]
The newest changes fixed the loading time problem completely. Not sure if that was the intention, but thank you very much for this as well as for this great piece of software!
