### ISSUE TITLE
[Suggestion] Automatic builds with GitHub actions.

### ISSUE THREAD

**Issue by g-yui** [digimezzo/dopamine#139]
I would like to suggest that you add a workflow through the Actions tab so new releases of Dopamine can automatically be built and published, that would make testing the software a lot easier for those that are interested in doing so but don't know/want to build from source themselves.

**Comment by digimezzo** [comment]
@g-yui Thanks for bringing this to my attention. I haven't looked at GitHub actions, but I will definitely do this.

**Comment by MulverineX** [comment]
I'm looking at the 2 passed action runs and can't find the artifacts, are they disabled temporarily while you fix issues with the mac build?

**Comment by g-yui** [comment]
No artifacts are uploaded just yet on main.yml, it's mostly a test run for all builds.
windows.yml does upload an artifact to a release draft, since I used it as somewhat of a testing ground.
I'll eventually update the main.yml to allow for draft creation and artifact uploading and then I'll push a PR to dopamine, that is, if Digimezzo doesn't do it himself by that time.

Also, see #157 for the MacOS build.

**Comment by MulverineX** [comment]
Well I'm not personally a Mac user, that was just a guess as to why artifacts aren't being uploaded. I'm talking about GH:A's feature where you can attach binaries to an action run, where they're downloadable in a zip, it's totally understandable if not every action run results in a Release.

**Comment by g-yui** [comment]
Ah, I'm not very well versed in how actions work, how would you implement that into the current main.yml file?

**Comment by MulverineX** [comment]
I don't remember what path Dopamine's builds are under, but this workflow is a good example

**Comment by MulverineX** [comment]
(edited)

**Comment by g-yui** [comment]
Currently testing, I'm unsure if release is indeed the folder I'm looking for but here goes nothing
[ci](https://github.com/g-yui/dopamine/actions/runs/1156314846)

**Comment by g-yui** [comment]
Well, I'll need to target the specific files, since it ended up taking way too much space, but it did work ;) 
https://github.com/g-yui/dopamine/actions/runs/1156314846

**Comment by MulverineX** [comment]
You could move them to another directory.

**Comment by g-yui** [comment]
I'm trying this for now ;) [main.yml](https://github.com/g-yui/dopamine/actions/runs/1156368972/workflow)

**Comment by digimezzo** [comment]
> I'm trying this for now ;) [main.yml](https://github.com/g-yui/dopamine/actions/runs/1156408285/workflow)

Looking good 👍. I like the idea of automatically building and publishing artifacts: at each release is logical, but I'm thinking also intermediate builds, maybe on each merge of a PR to master? That would allow adventurous users to test out pre-previews 😜. I'll think about it a bit more.

**Comment by MulverineX** [comment]
You can probably massively cut down on the build time by compiling all three on a single macOS run.

**Comment by MulverineX** [comment]
Yikes. I would look into using another library.

**Comment by g-yui** [comment]
I can't find the folder and I've tried three times, pain TwT
Here's hoping [this](https://github.com/g-yui/dopamine/actions/runs/1156524135) build works

**Comment by g-yui** [comment]
Alas, it works now, after giving up and reading the small documentation for uploading artifacts. It just works now (・ω・)
I have it on workflow dispatch since changing it with push meant a lot of small annoyances while writing it, this can be easily changed by erasing the comment character in  "#push:" , also made a PR (#163) for it, later I'll make a check to see if it was triggered via workflow to make a new release out of it, but that'll have to wait for now ;)

**Comment by digimezzo** [comment]
> Yikes. I would look into using another library because that's super inefficient.

Better-sqlite3 was selected after weeks of research and testing. I would have preferred a Javascript library, in order to be able to build for all systems on 1 OS. But there is just none that is as performant as better-sqlite3. Also, JS libraries load the whole database in memory, which was not an option. As for winning build time, the 3 builds run in parallel, so it's probably faster as it is now than running the builds on 1 OS after one another.

**Comment by MulverineX** [comment]
I didn't say slower, I said inefficient. But fair enough if you couldn't find a better native library. Definitely better than the alternative (in-memory), especially for 4gb memory devices with big libraries.

**Comment by g-yui** [comment]
I had one such system a long time ago, would've definitely destroyed it, since it already was struggling with ram usage due to Windows and my then browser of choice.
The ram usage of the current Dopamine build is rather good for the amount of music I throw at it, and I bet most of the current ram usage is just Electron being Electron. It just needs to fix #158 and what's left of #129 to be incredibly CPU efficient as well, which is what I'm personally looking for in a music player 😄 
Also I'd say that running the three builds in parallel is more efficient all things considered, since the resources for the CI come from Github and not from Digimezzo himself, otherwise your point would be completely valid regarding the inefficiency of the resources for building.
