### ISSUE TITLE
In artist view, if the selected artist is only the album artist und not the "artist", the album isn't shown in the grid.

### ISSUE THREAD

**Issue by neubland** [digimezzo/dopamine#141]
This is easiest to notice with Various-Artist-Albums, but is true with collaboration albums too. Notice that on the right the various "Various Artist" albums are listed, but in the middle there is no album shown. This seems to be the case for every album where individual song artist and album artist differ.

![image](https://user-images.githubusercontent.com/34939446/125198763-8838de00-e263-11eb-8e5b-447ab13d5a66.png)

**Comment by digimezzo** [comment]
@neubland Thank you for reporting this bug. It is fixed in commit e8a320ef70aaf4b980a9c55f94223332c899c58c and will be in Preview 2.
