### ISSUE TITLE
Misplaced UI bar on startup

### ISSUE THREAD

**Issue by areas0** [digimezzo/dopamine#143]
![image](https://user-images.githubusercontent.com/59089509/125520807-05bd804e-5818-4837-a13b-32e149ac6b1c.png)
The blue bar above album isn't at the right place when starting Dopamine. (Alignment issue). Toggling makes it appear at the right place however.
Expected:
![image](https://user-images.githubusercontent.com/59089509/125520879-feafb7c0-2f92-4032-9f86-a5701439e0f0.png)
This bug seems to happen with the tabs after the first one (artist is fine)

Edit:
OS: Windows 10 21H1
Screen resolution: 1920x1080
Dopamine Preview 1

**Comment by g-yui** [comment]
Bug persists in Dopamine Preview 2.

OS: Windows 11 21H2
Screen resolution: 1360x720

**Comment by digimezzo** [comment]
Note to self. Check out this link: https://stackoverflow.com/questions/59017741/mat-ink-bar-location-not-update-when-container-resizes
