### ISSUE TITLE
[Suggestion] Add click interaction to album art to open Now Playing

### ISSUE THREAD

**Issue by MulverineX** [digimezzo/dopamine#145]
N/A

**Comment by digimezzo** [comment]
@MulverineX  Could you explain a bit more how this is supposed to work? Thanks.

**Comment by MulverineX** [comment]
When you're not on the Fullscreen now Playing screen, clicking the album art of the current song should open said screen.

**Comment by digimezzo** [comment]
@MulverineX Do you mean here?

![image](https://user-images.githubusercontent.com/11945339/126062338-45a3f13f-db1f-4634-8481-7b14b9c5ec2f.png)

**Comment by MulverineX** [comment]
@digimezzo Yes
