### ISSUE TITLE
Incorrect number of artists displayed

### ISSUE THREAD

**Issue by TurtleP** [digimezzo/dopamine#148]
Hey,

Not sure if it's a bug or intended.. behavior(?), but while working on my own program earlier that deals with audio metadata, my own Artist count was wrong (for showing stats). Anyways, it seems Dopamine is showing by the `ARTIST` metatag instead of `ALBUMARTIST`. Specifically, Dopamine shows `98` artists and Groove Music shows `91`. I only found out because of this:

**Dopamine 3**
![image](https://user-images.githubusercontent.com/6239208/126051629-bd7fbb2a-2c86-4197-88f8-dc8eb3dcd4d2.png)

**Groove Music**
![image](https://user-images.githubusercontent.com/6239208/126051637-054b53a9-422b-4817-a6d3-b7d2bf7384b2.png)

Although maybe Groove Music is the one which is incorrect? I don't know. Let me know your thoughts on this. There's probably a reason Dopamine uses `ARTIST` instead of `ALBUMARTIST`.

**Dopamine Version**: 3.0, Preview 2
**Operating System**: Windows 10 21H1

Best,
TurtleP

**Comment by digimezzo** [comment]
@TurtleP Could you click on the artists counter at the top of the artists list. It's a button to toggle between album artists, song artists and all artists.

![image](https://user-images.githubusercontent.com/11945339/126059364-4ce8661c-1ef5-4a64-9ac3-12cbb325309d.png)

Could you check if the artists count is then ok? Thanks.

**Comment by TurtleP** [comment]
Yeah, showing Album Artists is displays the correct number. I find it odd, though, since as far as I'm aware, the default should probably be Album Artists. Though that's just me. Anyways, thanks for letting me know.
