### ISSUE TITLE
An error has occurred which will cause the application to close.

### ISSUE THREAD

**Issue by captnalexx** [digimezzo/dopamine#155]
I get the following error when trying to start Dopamine 3:
"An error has occurred which will cause the application to close. Please verify the log if you need more information."

OS is Windows, used the Dopamine.Setup.3.0.0-preview.3.exe to install.

Attached below is the log file.

[Dopamine.log](https://github.com/digimezzo/dopamine/files/6962590/Dopamine.log)

**Comment by digimezzo** [comment]
This issue is fixed in preview 4.
