### ISSUE TITLE
Sufficiently long title names get displayed through the whole UI

### ISSUE THREAD

**Issue by g-yui** [digimezzo/dopamine#156]
Yup, they do, never noticed it before since most songs have short titles, but one in my library didn't, long live unnecessarily long Japanese song titles!!!
Matter of fact, I took a random song from my library and renamed it just to see what it would do and here you go!

![img](https://user-images.githubusercontent.com/79342645/129765499-c6a2c3fb-31f0-4a70-8853-e65f4f4a5deb.png)

This is the expected behavior

![img2](https://user-images.githubusercontent.com/79342645/129765120-84cba583-a0e3-4973-b0c8-524888b118e2.jpg)

Maybe aside from just dotting the rest of the title string you could slowly scroll it, just sayin' ;)

Keep up the good work 👍 

- Edit
I think something's leaking, since CPU usage increases per each song played, got from 0.34% CPU usage to almost 4% through my testing. To recreate you can just boot up Dopamine and just start clicking on the next song for a bit, memory doesn't seem to leak thus far though, always returning to 275-ish MB for Private Bytes and 170-ish MB for Private WS (this latter one being the one you can see in the Windows Task Manager as RAM usage).

**Comment by g-yui** [comment]
This was the song that tipped me off btw lol
![img](https://user-images.githubusercontent.com/79342645/129766462-cfea6901-bcb8-47f2-ba04-faabe76d9798.png)

**Comment by digimezzo** [comment]
Thank you for reporting this. I've fixed the long title problem. As for CPU usage, I've created a separate issue #158, so that I can close this issue concerning long title names.
