### ISSUE TITLE
Bold text looks very blurry on Windows

### ISSUE THREAD

**Issue by g-yui** [digimezzo/dopamine#164]
The blur comes back to take revenge for the last time you tried to take it out 😨 

![img](https://user-images.githubusercontent.com/79342645/130375045-a7f3ee32-740f-46a6-9aa2-e79119482b8d.jpg)

Frankly I have no idea why this happens.

Latest source code build, [this one](https://github.com/g-yui/dopamine/runs/3395544944?check_suite_focus=true) specifically.
OS: Windows 11.

**Comment by digimezzo** [comment]
Did you also have this problem on Windows 10?

**Comment by digimezzo** [comment]
I'm having the same problem on Windows 10. It seems that only bold font are affected. I'll try to find out what's happening.
![image](https://user-images.githubusercontent.com/11945339/130410866-1cc6cf19-7dae-456e-a8a6-521cb03bc442.png)

**Comment by digimezzo** [comment]
It might be related to this: https://stackoverflow.com/questions/21332475/bold-fonts-in-google-chrome-are-blurry-font-face
I, indeed, don't specify a bold font-face for opensans (that's the font that is used in the UI). So Chrome/ Electron might try to create its generate bold via an algorithm, which is not as pretty as real bold. I'll try to fix this tonight.

**Comment by g-yui** [comment]
Yup, that did the job. Nicely done!
