### ISSUE TITLE
Dopamine3-installation doesn't work on Ubuntu or Mint with Gnome

### ISSUE THREAD

**Issue by Dan-cer** [digimezzo/dopamine#167]
I failed to get Dopamine 3 preview 4 starting on my Linux Mint Cinnamon, tried it with both .AppImage and .deb file.
In both cases there only is a launch icon on my taskbar and a white empty window.

Researching about AppImage showed me that there is a general problem to get AppImages work on Gnome platforms.

**Comment by digimezzo** [comment]
@Dan-cer Could you send me the log file? It's in .config/Dopamine/logs/

**Comment by Dan-cer** [comment]
Yes, sure:

Digimezzo schrieb am Dienstag 24 August 2021 11:42:34 (+02:00):



@Dan-cer Could you send me the log file? It's in .config/Dopamine/logs/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
[2021-08-23 17:38:26.150] [info]  [Main] [] +++ Starting +++
[2021-08-23 17:41:39.469] [info]  [App] [window-all-closed] +++ Stopping +++
[2021-08-23 17:46:03.109] [info]  [Main] [] +++ Starting +++
[2021-08-23 17:46:57.788] [info]  [App] [window-all-closed] +++ Stopping +++
[2021-08-23 17:47:01.983] [info]  [Main] [] +++ Starting +++
[2021-08-23 17:47:02.156] [info]  [Main] [] +++ Starting +++
[2021-08-23 17:47:02.462] [info]  [Main] [] Attempt to run second instance. Showing current window.
[2021-08-23 17:47:02.466] [info]  [Main] [] There is already another instance running. Closing.
[2021-08-23 17:47:03.856] [info]  [Main] [] +++ Starting +++
[2021-08-23 17:47:03.864] [info]  [Main] [] Attempt to run second instance. Showing current window.
[2021-08-23 17:47:03.864] [info]  [Main] [] There is already another instance running. Closing.
[2021-08-23 17:50:36.407] [info]  [App] [window-all-closed] +++ Stopping +++
[2021-08-23 17:50:47.061] [info]  [Main] [] +++ Starting +++
[2021-08-23 17:50:49.057] [info]  [Main] [] +++ Starting +++
[2021-08-23 17:50:49.063] [info]  [Main] [] Attempt to run second instance. Showing current window.
[2021-08-23 17:50:49.064] [info]  [Main] [] There is already another instance running. Closing.
[2021-08-23 17:50:52.108] [info]  [App] [window-all-closed] +++ Stopping +++
[2021-08-23 17:57:18.839] [info]  [Main] [] +++ Starting +++
[2021-08-23 17:57:24.211] [info]  [App] [window-all-closed] +++ Stopping +++
[2021-08-24 06:03:07.326] [info]  [Main] [] +++ Starting +++
[2021-08-24 06:03:25.632] [info]  [App] [window-all-closed] +++ Stopping +++

**Comment by digimezzo** [comment]
When the white window is showing, could you press F12 on you keyboard and go to the "Console" tab? Then please paste the content of the console tab here.

**Comment by Dan-cer** [comment]
The result is attached.

Digimezzo schrieb am Dienstag 24 August 2021 11:56:55 (+02:00):



When the white window is showing, could you press F12 on you keyboard and go to the "Console" tab? Then please paste the content of the console tab here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
Uncaught Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.org.chromium.Chromium.d7z25b)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5)
    at Module.load (internal/modules/cjs/loader.js:935)
    at Module._load (internal/modules/cjs/loader.js:776)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    at Module.require (internal/modules/cjs/loader.js:959)
    at require (internal/modules/cjs/helpers.js:88)
    at bindings (/opt/Dopamine/resour…ngs/bindings.js:112)

**Comment by Dan-cer** [comment]
BTW: I have to start Dopamin with terminal, because there is no launcher yet in the menu.

Digimezzo schrieb am Dienstag 24 August 2021 11:56:55 (+02:00):



When the white window is showing, could you press F12 on you keyboard and go to the "Console" tab? Then please paste the content of the console tab here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by digimezzo** [comment]
What version of Linux Mint Cinnamon are you using? I need to try it out.

**Comment by Dan-cer** [comment]
20.2, the latest release.

Digimezzo schrieb am Dienstag 24 August 2021 12:32:43 (+02:00):



What version of Linux Mint Cinnamon are you using? I need to try it out.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sivajone** [comment]
same problem on debian 11 
![image](https://user-images.githubusercontent.com/48877780/130611816-835304e5-fac8-4561-b222-c49e2be3b085.png)

**Comment by Dan-cer** [comment]
Yes, here is an article about AppImages:
https://www.techrepublic.com/article/why-i-have-a-problem-with-appimages-on-linux/

Sivaj schrieb am Dienstag 24 August 2021 13:53:46 (+02:00):



same problem on debian 11


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sivajone** [comment]
> Yes, here is an article about AppImages:
> https://www.techrepublic.com/article/why-i-have-a-problem-with-appimages-on-linux/
> 
> Sivaj schrieb am Dienstag 24 August 2021 13:53:46 (+02:00):
> 
> 
> 
> same problem on debian 11
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

i used Debian package and btw i use KDE

**Comment by Dan-cer** [comment]
Oh, then KDE is not without problems here as well.

Sivaj schrieb am Dienstag 24 August 2021 13:58:48 (+02:00):



Yes, here is an article about AppImages:
https://www.techrepublic.com/article/why-i-have-a-problem-with-appimages-on-linux/

Sivaj schrieb am Dienstag 24 August 2021 13:53:46 (+02:00):

same problem on debian 11

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

i used Debian package and btw i use KDE

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by digimezzo** [comment]
There are different things going on here. 

First of all, AppImages aren't evil, as stated in the article. The article is just a personal opinion of a AppImage hater. There is no technical information in the article as of why AppImage is not good. AppImage has its limitations (I experienced that I could not set file associations to Dopamine with the AppImage installer). Other than that, AppImage is rather great if you don't want to pollute your system with 3rd party libs.

Second, to have desktop integration when using the AppImage, it is required to install AppImageLauncher. This is their GitHub page (https://github.com/TheAssassin/AppImageLauncher), but the installer of AppImageLauncher should also be in your favorite package manager. Once installed, when you select to execute the AppImage, AppImageLauncher will ask you if you want to integrate it in your system. Basically, a .desktop file is created for the AppImage.

Third, the issue with the white screen has nothing to do with AppImages. It also happens with the .deb. It is caused by a missing GLIBC_2.33 on debian,Ubuntu LTS and Mint (which is based on Uubntu LTS). This problem is caused because I built Dopamine on a Linux distribution that is more up to date than Debian and Ubuntu LTS. Now that I have GItHub actions set up however,I'm building on Ubuntu LTS, and that creates installers that work (I tested it right now on Mint 20.2). Dopamine3.0 Preview 5 will solve your issue. Thanks for reporting this problem and for you patience for the solution.

**Comment by Dan-cer** [comment]
Thank you so much for your very detailed answer.


Have I to wait for Preview 5 then? Or am I able to use the AppImage of 4 using the Launcher? 
I'm excited to try it out, so I will try the 4.


And thank you for your great work and quick improvements!

Digimezzo schrieb am Dienstag 24 August 2021 19:02:12 (+02:00):



There are different things going on here.

First of all, AppImages aren't evil, as stated in the article. The article is just a personal opinion of a AppImage hater. There is no technical information in the article as of why AppImage is not good. AppImage has its limitations (I experienced that I could not set file associations to Dopamine with the AppImage installer). Other than that, AppImage is rather great if you don't want to pollute your system with 3rd party libs.

Second, to have desktop integration when using the AppImage, it is required to install AppImageLauncher. This is their GitHub page (https://github.com/TheAssassin/AppImageLauncher), but the installer of AppImageLauncher should also be in your favorite package manager. Once installed, when you select to execute the AppImage, AppImageLauncher will ask you if you want to integrate it in your system. Basically, a .desktop file is created for the AppImage.

Third, the issue with the white screen has nothing to do with AppImages. It also happens with the .deb. It is caused by a missing GLIBC_2.33 on debian,Ubuntu LTS and Mint (which is based on Uubntu LTS). This problem is caused because I built Dopamine on a Linux distribution that is more up to date than Debian and Ubuntu LTS. Now that I have GItHub actions set up however,I'm building on Ubuntu LTS, and that creates installers that work (I tested it right now on Mint 20.2). Dopamine3.0 Preview 5 will solve your issue. Thanks for reporting this problem and for you patience for the solution.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by digimezzo** [comment]
Preview 4 won't work, even with AppImage launcher. Because the problem has nothing to do with that. You'll need to wait until Preview 5. I'll try to have it ready very quickly.

**Comment by Dan-cer** [comment]
Good to know, thanks.

Digimezzo schrieb am Dienstag 24 August 2021 19:15:31 (+02:00):



Preview 4 won't work, even with AppImage launcher. Because the problem has nothing to do with that. You'll need to wait until Preview 5. I'll try to have it ready very quickly.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by digimezzo** [comment]
@Dan-cer I've updated the .AppImage and .deb in the Preview 4 release. They should now work. Could you try them out?

**Comment by Dan-cer** [comment]
The AppImage is starting and working.
To use the .deb have I to add `GLIBC_2.33`? BC I can't find it within my synaptic.

Digimezzo schrieb am Dienstag 24 August 2021 19:52:29 (+02:00):



@Dan-cer I've updated the .AppImage and .deb in the Preview 4 release. They should now work. Could you try them out?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by digimezzo** [comment]
@Dan-cer You don't have to install glibc. The .deb should also work now.

**Comment by Dan-cer** [comment]
AppImage is running fine. However, the AppImageLauncher hasn't created a .desktop starter automatically. Have I to do it manually now, or is there another solution?


BTW: How can I use my playlists? Is there no playlist-feature integrated yet?

Digimezzo schrieb am Dienstag 24 August 2021 19:52:29 (+02:00):



@Dan-cer I've updated the .AppImage and .deb in the Preview 4 release. They should now work. Could you try them out?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dan-cer** [comment]
OK, there is an installation in /opt/dopamine, and there is a .desktop file in /usr/share/applications.


However, that file doesn't work yet. Wrong Exec?
I attached the code.

Digimezzo schrieb am Dienstag 24 August 2021 23:09:43 (+02:00):



@Dan-cer You don't have to install glibc. The .deb should also work now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by digimezzo** [comment]
There is no playlists support yet, but that's coming soon. I don't know why the desktop file doesn't work. Could you attach the content? I don't see it now.
