### ISSUE TITLE
Improve Linux UI integration

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine#172]
Small improvements to theming to improve integration with Linux:

- Add separate theming for scrollbars
- Allow centering of album info text
- Change album selector so it looks good when the album info pane has no background

**Comment by MulverineX** [comment]
Would be way easier to just add #159... Manual CSS configuration is nothing new for light power users of Linux.

**Comment by digimezzo** [comment]
#159 will probably never happen. A few reasons on the top of my head:

- Positioning UI elements is already challenging, even without users doing their own thing.
- The CSS classes will probably change a lot while the software grows, which will break theming.
- Maintaining such customizability on the long run will be a crazy job for me. Each time I want to change something or add functionality, I must make sure that I don't break theming.
- The theme files will be too complex for most users. Not all users are Linux users and not all Linux users know CSS.

**Comment by digimezzo** [comment]
Fixed in e9d66585f7c1932b5825cd7c0074c15558d015f2
