### ISSUE TITLE
Preview 6 Controls dont work

### ISSUE THREAD

**Issue by Muspellheimer** [digimezzo/dopamine#183]
Im using win11 insider build and i did use preview 4 until now

I just downloaded preview 6 and it seems like there is something wrong with the interface.
after installing pre6 i can not click on any element located below the progress bar.

the progrees bar itself works just fine like everything else.
nothing is clickable below the bar.

**Comment by digimezzo** [comment]
@Muspellheimer Thank you for logging this issue. it's indeed broken. I've removed the downloads for preview 6 for now and will fix this bug in preview 7 today.
