### ISSUE TITLE
External Music Drive

### ISSUE THREAD

**Issue by Crocodile73** [digimezzo/dopamine#185]
version 3 preview 7. Does not load any music from an external drive.

[2021-09-20 14:49:05.960] [error] [IndexablePathFetcher] [getIndexablePathsForSingleFolderAsync] Error occurred while getting files recursively. Error EPERM: operation not permitted, lstat 'M:\\System Volume Information'

**Comment by digimezzo** [comment]
@Crocodile73 Could you add your whole log file? I need more info to understand this problem.

**Comment by Crocodile73** [comment]
[Dopamine.log](https://github.com/digimezzo/dopamine/files/7209577/Dopamine.log)

**Comment by digimezzo** [comment]
Hmm, I expected more from the logs :( I can only see that it fails to read the "System Volume Information" folder on the M: drive, which is normal. Could you also attach your Dopamine.db?

**Comment by Crocodile73** [comment]
[Dopamine.zip](https://github.com/digimezzo/dopamine/files/7211231/Dopamine.zip)

i have had no issues etc with version 2.

**Comment by digimezzo** [comment]
Where is your music located on the M: drive? Are the music files in subfolder?

**Comment by Crocodile73** [comment]
yes M Drive, then sorted as normal in there own folders. so like m:\coldplay - rushofbloodtothehead\(all the music files)

**Comment by jbaylies** [comment]
for the record I've had no issues with a large external network drive.

windows 10, dopamine v3.0.0-preview7

**Comment by Crocodile73** [comment]
Any fix for this issue yet?

**Comment by digimezzo** [comment]
> Any fix for this issue yet?

No yet unfortunately. I'm not having this issue over here. That doesn't help in fixing it.

**Comment by Crocodile73** [comment]
Yes I will test when ready, no problem.

**Comment by digimezzo** [comment]
Issue hopefully fixed in commit 0189d77903475d64ac8b36c3fcf24a8895a7dfab. Issue remains open until confirmation from @Crocodile73. The test preview will be ready today in a few hours.

**Comment by digimezzo** [comment]
@Crocodile73 The preview containing the possible fix is available here: https://github.com/digimezzo/dopamine/releases/tag/v3.0.0-preview10-fix-issue-185

**Comment by Crocodile73** [comment]
That is working fine now for me. Great job.
