### ISSUE TITLE
Add Last.fm support

### ISSUE THREAD

**Issue by SIVAH-AKASH** [digimezzo/dopamine#214]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report  
[x] Feature request
</code></pre>

Feature request for adding support for Last.fm scrobbling in Dopamine 3.
I believe we are supposed to log issues for Dopamine 3 also here. Apologies if that is not the case.

**Comment by digimezzo** [comment]
Hi @SIVAH-AKASH. Last.fm support is coming. The plan is to add all features of Dopamine 2 to Dopamine 3.

**Comment by digimezzo** [comment]
Note to self: add love button.

![image](https://user-images.githubusercontent.com/11945339/202996335-5a1ada3f-aa73-4fcf-a569-1e255d7fbe1f.png)

**Comment by digimezzo** [comment]
Fixed in a6ba21888196221a7e1a3796b656afb825078755

**Comment by SIVAH-AKASH** [comment]
Awesome! Thanks!
