### ISSUE TITLE
Add "random" albums sort order

### ISSUE THREAD

**Issue by Seraaron** [digimezzo/dopamine#220]
One of my favorite features of [Lollypop](https://www.flathub.org/apps/details/org.gnome.Lollypop) is the 'recently added' tab, which sorts my music in the order it was added to my library. I love this feature because it makes it really easy to find and listen to new music as soon as I download it.

Similarly, the 'random' sort order for albums in Lollypop is nice too, since that sometimes shows me old music that I haven't heard for a while. (Being shown a selection of random albums to choose from is better than just clicking shuffle all and skipping until you see an album you like, imo).

Maybe these are already featues, but I haven't noticed it if they are?

**Comment by digimezzo** [comment]
Hi! Thanks for the suggestions. 

You should be able to replicate the 'recently added' featuer of Lollipop by changing the sorting in any of the album view to 'By date added' (click on A-Z to cycle between the available options). I can add the 'random' album order there too in a next preview.

![image](https://user-images.githubusercontent.com/11945339/158556404-b0ba7b29-5949-4459-bd83-1e79010b9de6.png)

**Comment by Seraaron** [comment]
Cheers!
