### ISSUE TITLE
Right click to add to playlist menu broken

### ISSUE THREAD

**Issue by Parzival5129** [digimezzo/dopamine#222]
Im using W11 and if I right click it and click on "add to playlist" nothing happens

**Comment by digimezzo** [comment]
Could you send me the log file? Are you sure there is a song selected when right-clicking? (there should be, but I'm trying to understand what is happening).

**Comment by Parzival5129** [comment]
@digimezzo Yeah ive tried both albums and songs
[Dopamine.log](https://github.com/digimezzo/dopamine/files/8209095/Dopamine.log)

**Comment by digimezzo** [comment]
Could you take a screenshot of your add to playlist menu and it's submenu's (if there are any).

Thanks!

**Comment by Parzival5129** [comment]
@digimezzo I can't go past the first one:
![image](https://user-images.githubusercontent.com/94785975/157494892-e3bdc2fe-3db4-4ca8-9a71-7faf584c8155.png)

**Comment by Parzival5129** [comment]
@digimezzo Oh I do have created 2 playlists already
![image](https://user-images.githubusercontent.com/94785975/157496891-bd1b719f-254b-4f6a-815d-f8faeda2ae7a.png)

**Comment by Parzival5129** [comment]
@digimezzo Seems like I have messed up Playlist Folders with actual Playlists. Should have taken a closer look on what I was doing
