### ISSUE TITLE
Add folder to playlist

### ISSUE THREAD

**Issue by Nicksden** [digimezzo/dopamine#237]
Hi! Thank you for your work, it's greatly appreciated!

I was wondering if it's possible to add a feature to enable adding songs to playlist from Folders tab or from "now playing" menu. If I have a folder with 5000 songs and each song has a different album and artist, it's very challenging to add all of these to a playlist.

**Comment by gregoftheweb** [comment]
+1
Ideally a right click context menu that lets you add to playlist.

I drive my playing via the folder view (15,000 tracks already organized) but I'd love a quick way to add to playlist.  That'd be sweet.

**Comment by digimezzo** [comment]
Fixed in 54f259552b6ca6365a78ac7780f1cbf75bb6e95b
