### ISSUE TITLE
Delete files definitly and play video mp4 files 

### ISSUE THREAD

**Issue by trimechee** [digimezzo/dopamine#244]
Hello, Dopamine player is wonrdeful and amazing ! thank you vey much ! please it wold be great if there is an option to have the ability to quickly and definitively delete files from the hard drive and option to play mp4 and video files, beacause sometimes, we download tv shows and documentaries and just want to listen when we go to sleep with the computer screen off, thank you very much!

**Comment by muspelll** [comment]
wtf???

**Comment by teremy** [comment]
I just searched for the play mp4 file feature. It shouldn't be too difficult to implement. I'd like to have this feature too.

**Comment by trimechee** [comment]
I hope so in sha Allah

**Comment by digimezzo** [comment]
Both features (MP4 audio playback and file delete) are quick to add. I'll do it for the next preview.

**Comment by trimechee** [comment]
Fantastic awesome !!! thank you very much 🥇
