### ISSUE TITLE
Add "Songs" screen

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine#248]
This is how it looked in Dopamine 2
![image](https://user-images.githubusercontent.com/11945339/195596119-9d2974d7-03f1-4cb7-a857-1d2fb559de0b.png)

![image](https://user-images.githubusercontent.com/11945339/196884040-3743d34f-0660-4b6c-b4e7-0c4c613029bc.png)

**Comment by tocotronaut** [comment]
Yeah, it would be nice to have a Song section.

**Comment by digimezzo** [comment]
Fixed in b35f0eefb1c5698005e1a934582752c2389b6373
