### ISSUE TITLE
Enabling Discord Rich Presence turns it off.

### ISSUE THREAD

**Issue by Blenux** [digimezzo/dopamine#270]
OS: Windows 10
Version: 3.0.0-preview.11

Installed and enable DRP during first setup.

Issue:  Toggle is reversed.
![Discord_lFZf0cuhwL](https://user-images.githubusercontent.com/25260650/180479930-bc0fca5c-a531-4350-a988-59677f951cb9.gif)

**Comment by Blenux** [comment]
Same Issue on Linux.

**Comment by digimezzo** [comment]
Thanks for reporting this. I found the problem and it will be fixed in the next preview.
