### ISSUE TITLE
Bug : Dopamine crashes with \\ in album artist field

### ISSUE THREAD

**Issue by YnopTafGib** [digimezzo/dopamine#272]
Dopamine crashes when clicking on an album with an album artist field containing a double backslash (\\\\) :
For example : 'Queen\\\\test' creates a separate album with a special character, removing the \\\\ fixes the issue.

![exemple](https://user-images.githubusercontent.com/52357185/181735189-1ff30369-7e2c-441f-a402-5c17349bc102.png)

**Comment by digimezzo** [comment]
Thanks for reporting this. I'll have a look at it.

**Comment by digimezzo** [comment]
Fixed in 63723046f426edb6a3d4b6504767d7c0d8d37bf6
