### ISSUE TITLE
Cannot compile if only VS Community 2022 is installed

### ISSUE THREAD

**Issue by allancm** [digimezzo/dopamine#279]
## I'm submitting a compilation issue

<pre><code>
</code></pre>

## I'm using these versions

* Windows version: Microsoft Windows [Version 10.0.22000.856]
* Dopamine version: master github version 
*Visual Studio Code
Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z (1 wk ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000
*Visual Studio 2022 Developer Command Prompt v17.2.6

## Reproduction steps

* Downloaded the code from github
* Running npm install gives errors
## Observed behavior

The compilation fails with the following error message:

Running npm install gives an error saying that 
*npm ERR! gyp info find Python using Python version 3.9.5 found at "C:\Program Files\Python39\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS running in VS Command Prompt, installation path is:
npm ERR! gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp ERR! find VS - will only use this version
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (F:\github\dopamine\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at F:\github\dopamine\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (F:\github\dopamine\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at F:\github\dopamine\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at F:\github\dopamine\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at F:\github\dopamine\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at F:\github\dopamine\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000

## Desired behavior

It should compile with no problem

**Comment by digimezzo** [comment]
@allancm  Did you install node.js including Tools for Native Modules? See Build prerequisites on Windows here: https://github.com/digimezzo/dopamine/blob/master/README.md

**Comment by allancm** [comment]
Yes I have installed:
* node --version
v16.15.1
* npm --version
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
8.11.0
* code --version
1.70.2
e4503b30fc78200f846c62cf8091b76ff5547662
x64
* git --version
git version 2.33.1.windows.1
* git log -1
commit 1043f9b91b9ef03019ed8486de095f650cffc14c (HEAD -> master, origin/master, origin/HEAD)
Author: Digimezzo Raphaël <raphael@digimezzo.com>
Date:   Mon Aug 15 07:33:10 2022 +0200

    Added German translation

It seems like the requisite somewhere from the Visual Studio 2022 Community was not expected as a later version of the required VS 2015.  Something is different in the directories structure.

**Comment by allancm** [comment]
Next step
![image](https://user-images.githubusercontent.com/2113118/186445595-608afb15-f7ad-4e79-b62f-56c7c8cdd67b.png)
![image](https://user-images.githubusercontent.com/2113118/186445639-53097fc8-826d-4980-91a0-154ebe3ab8e1.png)
![image](https://user-images.githubusercontent.com/2113118/186445999-f98bcec0-df99-476b-b818-76d2b9b552d1.png)
![image](https://user-images.githubusercontent.com/2113118/186447210-c2126dd5-5753-4b55-8232-6320e9fa3045.png)

* Posting this because the reboot will probably clean those images

**Comment by allancm** [comment]
After I reboot the machine, I think I am now closer with only the following errors in section postinstall

> Dopamine@3.0.0-preview.12 postinstall
> npm run postinstall:electron && electron-builder install-app-deps && ngcc


> Dopamine@3.0.0-preview.12 postinstall:electron
> node postinstall

  • electron-builder  version=22.5.1
  • loaded configuration  file=F:\github\dopamine\electron-builder.json
  • rebuilding native dependencies  dependencies=better-sqlite3@7.1.2, register-scheme@0.0.2 platform=win32 arch=x64
  • install prebuilt binary  name=better-sqlite3 version=7.1.2 platform=win32 arch=x64
  • build native dependency from sources  name=better-sqlite3
                                          version=7.1.2
                                          platform=win32
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.6
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ C:\Users\xxxxx\AppData\Local\npm-cache\_prebuilds\75c7aa-better-sqlite3-v7.1.2-electron-v87-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/JoshuaWise/better-sqlite3/releases/download/v7.1.2/better-sqlite3-v7.1.2-electron-v87-win32-x64.tar.gz
    prebuild-install http 404 https://github.com/JoshuaWise/better-sqlite3/releases/download/v7.1.2/better-sqlite3-v7.1.2-electron-v87-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=12.0.16 runtime=electron arch=x64 libc= platform=win32)

  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path F:\github\dopamine\node_modules\register-scheme
    npm ERR! command failed
    npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\xxxxx\AppData\Local\Temp\install-d3da095b.cmd
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@7.1.2
    npm ERR! gyp info using node@18.7.0 | win32 | x64
    npm ERR! gyp info find Python using Python version 3.10.6 found at "C:\Python310\python.exe"
    npm ERR! gyp info find VS using VS2019 (16.11.32802.440) found at:
    npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
    npm ERR! gyp info find VS run with --verbose for detailed information
    npm ERR! (node:8252) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
    npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
    npm ERR! gyp info spawn C:\Python310\python.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'F:\\github\\dopamine\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'msvs',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'F:\\github\\dopamine\\node_modules\\register-scheme\\build\\config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'F:\\github\\dopamine\\node_modules\\node-gyp\\addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\xxxxx\\.electron-gyp\\12.0.16\\include\\node\\common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xxxxx\\.electron-gyp\\12.0.16',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=F:\\github\\dopamine\\node_modules\\node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\xxxxx\\\\.electron-gyp\\\\12.0.16\\\\<(target_arch)\\\\node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=F:\\github\\dopamine\\node_modules\\register-scheme',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'F:\\github\\dopamine\\node_modules\\register-scheme\\build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
    npm ERR! gyp ERR! configure error
    npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (F:\github\dopamine\node_modules\node-gyp\lib\configure.js:351:16)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    npm ERR! gyp ERR! System Windows_NT 10.0.22000
    npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\github\\dopamine\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    npm ERR! gyp ERR! cwd F:\github\dopamine\node_modules\register-scheme
    npm ERR! gyp ERR! node -v v18.7.0
    npm ERR! gyp ERR! node-gyp -v v7.1.2
    npm ERR! gyp ERR! not ok

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\xxxxx\AppData\Local\npm-cache\_logs\2022-08-24T15_08_28_624Z-debug-0.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js' rebuild better-sqlite3@7.1.2 register-scheme@0.0.2
                    workingDir=
npm ERR! code 1
npm ERR! path F:\github\dopamine
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c C:\Users\xxxxx\AppData\Local\Temp\postinstall-9c3f91f1.cmd

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxx\AppData\Local\npm-cache\_logs\2022-08-24T15_08_12_316Z-debug-0.log

**Comment by digimezzo** [comment]
It's the building of the native libraries for better-sqlite3 that fails. I've struggled with that too in the past. It remains a challenge. They have prebuilt libraries to facilitate this process now. I'm checking it out now, but using those libraries requires that I update the version of better-sqlite3 and electron that I'm currently use. That introduces breaking changes that I need to resolve. So it might take a few days. I'll keep you updated.

**Comment by digimezzo** [comment]
I've now updated to more recent versions of electron and better-sqlite3. This should make the compilation much easier.

**Comment by allancm** [comment]
It seems that something else (not dopamine) installed me MS Build tools 2019.  I just uninstall that, and now it compiled successfully! 
The npm install is now working fine.
The npm start is giving me now this error:


> Dopamine@3.0.0-preview.12 start
> npm run postinstall:electron && npm-run-all -p ng:serve electron:serve


> Dopamine@3.0.0-preview.12 postinstall:electron
> node postinstall


> Dopamine@3.0.0-preview.12 ng:serve
> ng serve --sourceMap=true


> Dopamine@3.0.0-preview.12 electron:serve
> wait-on http-get://localhost:4200/ && npm run electron:serve-tsc && electron . --serve --remote-debugging-port=9222

10% building 3/3 modules 0 active(node:20556) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
10% building 3/4 modules 1 active ...pack-dev-server\client\index.js?http://0.0.0.0:0/sockjs-node&sockPath=/sockjs-nodenode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (F:\github\dopamine\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (F:\github\dopamine\node_modules\webpack\lib\NormalModule.js:417:16)
    at F:\github\dopamine\node_modules\webpack\lib\NormalModule.js:452:10
    at F:\github\dopamine\node_modules\webpack\lib\NormalModule.js:323:13
    at F:\github\dopamine\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at F:\github\dopamine\node_modules\loader-runner\lib\LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (F:\github\dopamine\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:46:13)
    at processResource (F:\github\dopamine\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders (F:\github\dopamine\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders (F:\github\dopamine\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (F:\github\dopamine\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (F:\github\dopamine\node_modules\webpack\lib\NormalModule.js:446:15)
    at Compilation.buildModule (F:\github\dopamine\node_modules\webpack\lib\Compilation.js:739:10)
    at F:\github\dopamine\node_modules\webpack\lib\Compilation.js:981:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.7.0
ERROR: "ng:serve" exited with 1.

**Comment by digimezzo** [comment]
It seems caused by node.js versions since v17 because they fixed a vulnerability, which now causes this error in combination with some packages. See: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported.

I recommend using the LTS version of node.js, which will resolve this issue. By the time a higher version becomes LTS, packages used by Dopamine will be updated and will support the new LTS version.

**Comment by allancm** [comment]
Ok, you were right!
I installed nvm and then set the version of node to the latest version of 16.  Avoid 18 (the one I had before)

Now everything compiles and the executables in windows work as expected.

The last update with the current versions used:


>code --version
1.70.2
e4503b30fc78200f846c62cf8091b76ff5547662
x64
>npm --version
8.15.0
>git --version
git version 2.33.1.windows.1
>nvm v
1.1.9
>git log -1
commit 0fb67297a1d31b9ad651011031d477df070e2ff3 (HEAD -> master, origin/master, origin/HEAD)
Author: Digimezzo Raphaël <raphael@digimezzo.com>
Date:   Sun Aug 28 21:25:02 2022 +0200

    Fixed unit tests

Thanks for all the help.  I think this can now be closed

**Comment by digimezzo** [comment]
That's great news! You're welcome :)
