### ISSUE TITLE
3.0 Preview 13 error

### ISSUE THREAD

**Issue by Crocodile73** [digimezzo/dopamine#288]
[2022-09-14 22:40:06.850] [info]  [Main] [] +++ Starting +++
[2022-09-14 22:40:14.241] [info]  [App] [window-all-closed] +++ Stopping +++

launch dopamine, and a white window opens and says it has to close, see log. Log is as above. Its all the information it gives. Preview 12 works fine.

**Comment by digimezzo** [comment]
Fixed in 2f2fc11e4ddd5738c82c05e643ea20c815101d72. using web technologies is hard sometimes. Their breaking changes have cost me multiple weeks of my life.
