### ISSUE TITLE
Preview 13 doesn't start on Windows 10

### ISSUE THREAD

**Issue by adem4ik** [digimezzo/dopamine#289]
Version: [3.0 Preview 13](https://github.com/digimezzo/dopamine/releases/tag/v3.0.0-preview13)
OS: Windows 10 x64

1. Download Dopamine-3.0.0-preview.13.exe
2. Install
3. Try to run Dopamine

Result: Error
![image](https://user-images.githubusercontent.com/4707112/190268109-b2faeb7f-f85f-446e-88a8-1d68e5127f07.png)
Pressing on 'View log' gives nothing, it just closes the whole application.

Log from AppData\Roaming\Dopamine\ doesn't seem informative at all:
```
[2022-09-15 01:41:14.554] [info]  [Main] [] +++ Starting +++
[2022-09-15 01:43:43.688] [info]  [App] [window-all-closed] +++ Stopping +++
```

Previous Preview 12 works finely on the same machine:
![image](https://user-images.githubusercontent.com/4707112/190268909-0d9fb3ff-41be-47c0-9138-4197e42a932a.png)

**Comment by digimezzo** [comment]
Fixed in 2f2fc11e4ddd5738c82c05e643ea20c815101d72. using web technologies is hard sometimes. Their breaking changes have cost me multiple weeks of my life.

**Comment by adem4ik** [comment]
Tested latest nightly build https://github.com/digimezzo/dopamine/actions/runs/3066503527 - Dopamine works now on Windows 10:
![image](https://user-images.githubusercontent.com/4707112/190616351-66adc877-1c7b-419b-b52c-376f9a0c3200.png)

**Comment by digimezzo** [comment]
Thanks for confirming!
