### ISSUE TITLE
Old copyright year in Information

### ISSUE THREAD

**Issue by adem4ik** [digimezzo/dopamine#290]
Version: : 3.0.0-preview.13
OS: Linux Manjaro

1. Open Menu - Information

Result: Copyright Digimezzo Ⓒ 2014 - 2021
Expected result: Copyright Digimezzo Ⓒ 2014 - **2022**

![image](https://user-images.githubusercontent.com/4707112/190270566-cde84faf-500e-45fe-8d3c-f83af4e6613a.png)

**Comment by digimezzo** [comment]
Thanks! I'll fix that. 
I have a question: did the fonts always look like on the screenshot? Because that is not how i intended for it to look like.

**Comment by digimezzo** [comment]
Thanks!
