### ISSUE TITLE
Bug -- Playlist cant be created on Windows 11

### ISSUE THREAD

**Issue by MichaelPrinceps** [digimezzo/dopamine#293]
After clicking ok button to create a playlist nothing happens after

And also nothing is shown on Albums section

**Comment by digimezzo** [comment]
You probably created a palylist folder. You still need to create a playlst in that folder. Other users have notified me that it is confusing and I'll try to make this more clear in the future.

**Comment by digimezzo** [comment]
Fixed in 76720aae321f3b1339755093434d73e531a1fdba
