### ISSUE TITLE
Can't play music from my NAS on Ubuntu GNU/Linux

### ISSUE THREAD

**Issue by fredericpetit02** [digimezzo/dopamine#298]
Hi,

I put last Dopamine version on both Windows 11 and Ubuntu 22.04 (.exe and .deb assets). Everything works great for local music but not for distant files from my NAS freebox delta. On Ubuntu i see the files but impossible to play them, song is not started.

I opened every needed ports, and files can be played on VLC.

**Comment by digimezzo** [comment]
Do the files play on Windows?

**Comment by fredericpetit02** [comment]
Yes on Windowe everything is fine.

Example for the file with path pasted from nautilus : `smb://freebox-server.local/volume%201000go/Musiques/Alessia%20Cara/Alessia%20Cara%20-%20Holiday%20Stuff%20(2020)%20Mp3%20320kbps/1. Make It To Christmas (Stripped).mp3`

Dopamine log :
`[2022-09-16 21:23:48.715] [info]  [PlaybackService] [play] Playing '/run/user/1000/gvfs/smb-share:server=freebox-server.local,share=volume%201000go/Musiques/Alessia Cara/Alessia Cara - Holiday Stuff (2020) Mp3 320kbps/1. Make It To Christmas (Stripped).mp3'`

**Comment by fredericpetit02** [comment]
HI,

I made a persistent mount in my fstab file for the NAS, rebuild a colleciton with this mount path and everything is great now :+1:

**Comment by digimezzo** [comment]
That's great news! Thanks for confirming.
