### ISSUE TITLE
[Bug] Installer hangs due to registry entry

### ISSUE THREAD

**Issue by p-yukusai** [digimezzo/dopamine#299]
The installer gets stuck, necessitating manual extraction of the package contents with 7zip.

![image](https://user-images.githubusercontent.com/85849071/190730191-ecc7e3e3-2853-4bae-b8ad-ffd8856f764a.png)

I believe it is due to having my default app storage setup to a drive separate from C:\ , like so:

![image](https://user-images.githubusercontent.com/85849071/190730529-ad0ef147-deb3-42b9-8509-c0ce3cd5cdcc.png)

I do not know how to log this issue to help further, as it is not easy to setup, but should you know how to I would gladly help debug the NSIS installer.

The OS is Windows 11 Home, installed to C:\ drive. All other applications and documents are saved to a separate D:\ drive.
As far as I know, all versions suffer from this bug.

**Comment by digimezzo** [comment]
I've done some reseach and stumbled upon this bug in electron-builder (which generates the installer): https://github.com/electron-userland/electron-builder/issues/4057

Could it be that you manually deleted the Dopamine folder at some point without using Uninstall in control panel?

**Comment by p-yukusai** [comment]
Apparently it had the entry in the registry even though this was a fresh install? 
Regardless, this was indeed the issue and uninstalling from the control panel and using the installer again solved it. Thank you.

**Comment by digimezzo** [comment]
Excellent! Thanks for checking that out. I'll re-open this issue though, so I remember to udpate electron-builder to a version that should not fail installing, even if the entry is in the registry.
