### ISSUE TITLE
Discord RPC not working on the macOS version

### ISSUE THREAD

**Issue by malwarepad** [digimezzo/dopamine#309]
The rich presence is not even appearing on Discord, like at all! I can provide more info, but this is a pretty generic problem and I think you can replicate it extremely easily.

**Comment by digimezzo** [comment]
Could you attach the log file? I'm not sure if anything concerning Discord will be logged, but it's a good place to start.
Also, while Dopamine is open, if you press F12, the developer console will open. In the console tab, are there any errors logged concerning Discord? Thanks.

**Comment by malwarepad** [comment]
Wow, that reply was quick! No, there are no errors on the console tab. I don't really know the location of the log file. I can provide it if you inform me about it.

**Comment by digimezzo** [comment]
I'm not sure where it's stored for Mac, but there's a trick to find the location of the log file (until I add a direct link):

- In Dopamine, go to Settings > Appearance
- Under "Color" click on "Add more themes". This will open the themes directory in your file explorer
- Go up 1 directory. There you'll see several directories, including the "logs" directory
- In the logs directory you'll find Dopamine.log. That's the log file.

**Comment by malwarepad** [comment]
[Dopamine.log](https://github.com/digimezzo/dopamine/files/9666489/Dopamine.log)
You're not going to have a good time scrolling through though, as I have used your app a lot.. The file is quite large (~=1.2K lines).

**Comment by digimezzo** [comment]
Thanks for the log. It didn't help unfortunately. But luckily, this problem seems to happen on all OS's, so I was able to pinpoint the issue. It'll be fixed in the next preview.

**Comment by malwarepad** [comment]
Yup, I told you it was generic.. Glad I was able to help!
