### ISSUE TITLE
Album artwork missing

### ISSUE THREAD

**Issue by ceejayemm** [digimezzo/dopamine#327]
I have been tracking this project intermittently for a while. I have been using the appimage version of Dopamine 11/12 for a while on MX Linux 21 and have recently update my desktop to  Plasma.  I then saw that release 16 was available so I downloaded the appimage version. The app seems fine, it plays all my albums without any problem - except ALL the album artwork has disappeared.  The library simply shows a Dopamine icon for each album. All the track information is correct.  I have tried a full manual refresh of the artwork, I have Automatic Refresh turned on and I have done a full manual scan too.

How can I fix this problem ?

Thanks

Chris

**Comment by digimezzo** [comment]
Have you tried the Refresh options in the Album covers tab too? If yes, and that didn't help, could you send me the log file? It's in ~/.config/Dopamine/logs.

Could you also check the folder ~/.config/Dopamine/Cache/CoverArt if there are any cover art files in there?

**Comment by ceejayemm** [comment]
After writing the issue log above I thought the only thing I havent tried is removing / readding the entire library.  I have now done this. Originally I had 330+ albums and 5000+ tracks and no album covers.  After readding my music library I have 11 albums and 154 songs but all the albums have artwork! It seems that NONE my .m4a albums are no longer recognised.

I have attached the log files as requested and yes I now have 11 album cover is the cache location.

Chris
[logs.zip](https://github.com/digimezzo/dopamine/files/9819586/logs.zip)

**Comment by digimezzo** [comment]
Thanks, that's helpful info. I changed the tag-reading library in preview 16. So that's most likely why your m4a files are now failing. I'll further investigate and try to provide a fix as soon as possible. 
I don't know if the following is a possibility, but do you think you could share one of some of those m4a files so I could perform some tests with them?

**Comment by ceejayemm** [comment]
I see that you have released Preview 17 which says it has a fix for this problem. I downloaded the 'appimage' version of this and installed it today.  I have:

- refreshed the existing library but still get only 11 albums and 154 tracks (there should be 330+/5500+) listed.
- dropped and reattached the library file system which causes an auto refresh - same as above.

In both cases I can see the number of tracks (5500+) being accessed when the refresh takes place but I still get none of my .m4a files being shown in the library.

Going to the 'Folders', lists all the albums and tranks. Selecting an album/track from a folder will, in some cases (I haven't figured out yet why or when this happens), play the relevant music.

Regards.

Chris

**Comment by digimezzo** [comment]
Could you share some of the m4a files that are not being indexed? That would be of great help, because for the m4a's that I tested, indexing went well.

**Comment by digimezzo** [comment]
I found a bug in the indexing logic. Files that Dopamine tried to index, but failed, are ignored the next time an indexing is performed. That sounds like what you are experiencing. I'll fix that. For your situation, I think that following steps should resolve your issue:

- Close Dopamine
- Delete Dopamine.db (for linux and mac Dopamine.db is in folder ~/.config/Dopamine, for Windows at %appdata%/Dopamine)
- Start Dopamine, add your music folder and perform an indexing

**Comment by ceejayemm** [comment]
Hi

I have carried out the steps noted above and I now have a fully populated Library and things works as they used to.

Many thanks

Chris

**Comment by digimezzo** [comment]
You're welcome! I'm glad it helped. I'll add an advanced option to reset the database for others in such situations, so they don't hav eto perform these manual steps.
