### ISSUE TITLE
OGG file metadata not being processed by application

### ISSUE THREAD

**Issue by RandomAccountt** [digimezzo/dopamine#341]
As shown in the following screenshots; files with the .ogg extension can be correctly tagged (done in Picard), but appear without data in Dopamine. The songs will play in dopamine as intended, but do not have an attached title, album art, artist name info etc. The songs can be opened in mpv and VLC, where the album art and title will display normally (i.e. the issue is not do to with the files themselves but the way Dopamine is processing them)

[
![Screenshot 2022-11-02 185331](https://user-images.githubusercontent.com/30158779/199577368-24d55c4b-7b71-49aa-834f-e79b74c4afeb.png)
![Screenshot 2022-11-02 185315](https://user-images.githubusercontent.com/30158779/199577372-6a3b35ff-cb75-46c4-bd50-d7bf0037331c.png)
](url)

**Comment by digimezzo** [comment]
Could you share one or some of those files so I can perform tests with them? Thanks!

**Comment by RandomAccountt** [comment]
I had to rename the file extension so that it would upload to GitHub. Change the `.zip` to `.ogg` once you've downloaded it :)
[calm3.zip](https://github.com/digimezzo/dopamine/files/9923435/calm3.zip)

**Comment by digimezzo** [comment]
Thanks!
