### ISSUE TITLE
Display non-embedded album art (Folder.jpg)

### ISSUE THREAD

**Issue by Not-Sure-Whats-Going-On** [digimezzo/dopamine#351]
Loving Dopamine - works well with large collection.  My problem is that I have only started embedding album art within files recently.  All of my collection has albums sorted by directory and each directory has the music and a single file called Folder.jpg in it but these are not recognised.  Is there a way to get Dopamine to display these external files as album art without embedding them please?

**Comment by digimezzo** [comment]
Hi! Are you using Dopamine in Windows, Linux or Mac? For Windows that should work. Dopamine looks at these files in the same directory as the audio files:

'front.png',
'front.jpg',
'front.jpeg',
'cover.png',
'cover.jpg',
'cover.jpeg',
'folder.png',
'folder.jpg',
'folder.jpeg',
'%filename%.png',
'%filename%.jpg',
'%filename%.jpeg'

Where %filename% contains the same name as the audio file. For Linux and Mac it only works if the artwork files are in lowercase (like in the list above). I forgot to take case-sensitiveness of file names for Unix-like systems in mind. I'll fix that in the next preview.

**Comment by Not-Sure-Whats-Going-On** [comment]
Thanks for your reply.  Yes, I am using Linux.  I changed all the Folder.* to folder.* all is good with the world again.   Cheers!:+1:
