### ISSUE TITLE
Albums not showing

### ISSUE THREAD

**Issue by Crocodile73** [digimezzo/dopamine#353]
![unknown_2022 11 14-18 46](https://user-images.githubusercontent.com/16454525/201742287-601c5524-755c-4363-8b91-e28061018c15.png)

scan completes and show all the albums. When reopening again, it only shows as the picture. build 17 and 18

**Comment by digimezzo** [comment]
It looks like it's not wrapping. What happens when you resize the Songs pane? Does it adapt the albums view?

**Comment by Crocodile73** [comment]
> It looks like it's not wrapping. What happens when you resize the Songs pane? Does it adapt the albums view?

It shows the next album and then the rest of the albums as expected after few seconds. But it reverts on restart to the same row, but with that one extra album.

**Comment by digimezzo** [comment]
Ok thanks. I'm hving it too now; I never noticed this before :) I'll fix it.

**Comment by Not-Sure-Whats-Going-On** [comment]
Me too. But I found that if I click on one of the displayed albums in the single row then wrap happens and everything displays OK.

**Comment by digimezzo** [comment]
It seems to happen when the artists tab is not the default selected tab. When the player opens, it quickly changes to the tab that it should select (the one that was selected when last opening the player). The calculation of the rows on the albums pane however occurs too soon (before the tab switch has occurred). That causes the bug. I'm still looking into which way is best to solve it.

**Comment by moopet** [comment]
I have the same issue, and though I can't grab a screenshot fast enough, the text on the left that says "123 Albums" has other text on top of it in the couple of seconds it takes for this page to first display. Perhaps it's a more global wrapping issue than just the cover art?
