### ISSUE TITLE
Dracula colors for Dopamine

### ISSUE THREAD

**Issue by effectspcbs** [digimezzo/dopamine#368]
Hello,

If anyone is interested i added the Dracula color scheme to a new theme, you'll find it attached. It's not really a complete theme as there's no light Dracula color palette so i just used the default light style.

This was tested on version 3.0.0-preview.16. For future references, is there a way to submit a theme as a PR ?
[Dracula.theme.txt](https://github.com/digimezzo/dopamine/files/10253697/Dracula.theme.txt)

**Comment by overestimate** [comment]
> For future references, is there a way to submit a theme as a PR ?

Dug through code a bit, and [`src/app/services/appearance/default-themes-creator.ts`](https://github.com/digimezzo/dopamine/blob/master/src/app/services/appearance/default-themes-creator.ts) is where default themes are defined. You should be able to add it there. Make sure to update the spec file, though.

Not an issue (should be a PR), let's close this.

**Comment by effectspcbs** [comment]
Thanks for your help, that code makes sense even with my minimal knowledge i should be able to add it and submit a PR. Closing this.
