### ISSUE TITLE
Add lyrics support

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine#374]
Also check out this package: https://www.npmjs.com/package/songlyrics

**Comment by asd990323** [comment]
I want to increase support for lyrics, just like Generation 2 products, and why is there no small window mode?

**Comment by digimezzo** [comment]
@asd990323 Lyrics support is coming in preview 20. Small window mode is for the previews after that. You can see a rough (meaning that features might shift around a bit) planning here: https://github.com/digimezzo/dopamine/milestones
