### ISSUE TITLE
Windows Compatibility 

### ISSUE THREAD

**Issue by aquirozc** [digimezzo/dopamine#375]
Since `README.MD` file makes no mention of a specific Windows Release being requiered to run the program, I tried to run the program on Windows 8 (NT 6.2) however it is unable to launch. So now Im wondering about what are the minimun requisites to run the program on Windows-based platforms.

**Comment by digimezzo** [comment]
It should run on Windows 7 and up. So this is unexpected. Could you attach the log file? It's in %appdata%\Dopamine\logs.
Thanks

**Comment by aquirozc** [comment]
There is no Dopamine folder under %appdata%, however while I was trying to build from source I got the very same error when trying to open VS Code, so issue is likely to have something to do with my Windows installation rather than the application itself. 

Closing issue. Sorry 

![image](https://user-images.githubusercontent.com/77245705/213939192-48f3db2f-baf2-4124-84ef-c782751827ce.png)
