### ISSUE TITLE
Last.fm scrobbling not working as expected.

### ISSUE THREAD

**Issue by iPodVideo** [digimezzo/dopamine#377]
Last.fm scrobbling is not working. I am logged in and have been listening to plenty of tracks in the past few days
![image](https://user-images.githubusercontent.com/53324563/215432350-2978e18e-bb5b-4149-9d9e-66f01f536f1c.png)
![image](https://user-images.githubusercontent.com/53324563/215432406-b2e85209-8919-4de9-a992-d46a17306f4f.png)
![image](https://user-images.githubusercontent.com/53324563/215432508-ca6e7718-1da0-43f3-a30a-0aecc6f7390a.png)

**Comment by iPodVideo** [comment]
it is currently 30/01 but the last.fm scrobbling hasn't worked since the 25th

**Comment by iPodVideo** [comment]
Ok I have done a bit more testing and this seems to be an intermittent issue. 
![image](https://user-images.githubusercontent.com/53324563/215445005-c83832c2-e79c-4db9-b4b0-a1b12d509260.png)

**Comment by digimezzo** [comment]
Why is the issue closed? Does it work now?

**Comment by iPodVideo** [comment]
Sorry didn't realise that I closed it. The issue still persists

**Comment by digimezzo** [comment]
is it always the same songs where scrobbling doesn't work? If yes, could you share a file that works and one that doesn't work? (You'll have to zip them in order to attach them to this issue). Thanks.

**Comment by iPodVideo** [comment]
Apologies for the delay but I will get those files to you asap

**Comment by digimezzo** [comment]
> Apologies for the delay but I will get those files to you asap

No problem. I'm looking forward to the files. Please also add info if it's always the same files that fail to scrobble. That would greatly help in troubleshooting.

**Comment by iPodVideo** [comment]
[Joji - Tick Tock.zip](https://github.com/digimezzo/dopamine/files/10610654/Joji.-.Tick.Tock.zip)
This is one of them
I only uploaded one because they take forever to upload

**Comment by alvanx** [comment]
Same issue here. It worked at first but now mostly doesn't. I'm on 3.0.0-preview.19, macOS 13.1, M1 Pro.

**Comment by iPodVideo** [comment]
The only solution i have for this is to keep logging back into last.fm every time you restart the app.
