### ISSUE TITLE
Certain songs go into their own albums

### ISSUE THREAD

**Issue by fishy20** [digimezzo/dopamine#380]
![Screenshot_8](https://user-images.githubusercontent.com/88381766/217572115-444f2c37-b98c-4bf5-b364-67593a3bfa4f.png)
![Screenshot_7](https://user-images.githubusercontent.com/88381766/217572120-321b71ab-4557-4f8b-94c7-e9ec48c5f7be.png)

**Comment by digimezzo** [comment]
It's probably because of misconfigured album artists tag. Please look at the Dopamine F.A.Q.: https://digimezzo.github.io/site/dopamine-faq, unter title **Why are some of my songs not grouped in one album?**
