### ISSUE TITLE
No theme variable for tooltip/button foreground colors

### ISSUE THREAD

**Issue by jayylmao** [digimezzo/dopamine#381]
When using a lighter accent color, the foreground color on tooltips and buttons can be difficult to read. These seem to be hardcoded to be #fff, so would it be possible to have a variable for these to let us change this in the theme file?

<img width="379" alt="image" src="https://user-images.githubusercontent.com/73204320/218284585-834d44f8-c9dc-4ec0-981f-f838c75b02a4.png">
<img width="332" alt="image" src="https://user-images.githubusercontent.com/73204320/218284609-8c62f3c8-d0d5-423e-b376-b7f957ea49d2.png">

**Comment by digimezzo** [comment]
That makes sense. Thanks for reporting it. I'm planning it for the next preview.
