### ISSUE TITLE
Some tracks from audio books being split into separate album

### ISSUE THREAD

**Issue by TVJohn56** [digimezzo/dopamine#385]
Some audio books are being randomly split in two. For example, Harry Potter book 1, 7 tracks have been put into one album and the remaining (over 400) tracks in another. I've been unable to find any difference in the tags on the seven tracks, and Dopamine v2 didn't do this.

![hpBug](https://user-images.githubusercontent.com/62610177/222136933-8380e77a-b989-4042-b076-0b5d6338873a.jpg)

**Comment by digimezzo** [comment]
Would you mind attaching you Dopamine database? It's Dopamine.db in folder **%appdata%\Dopamine** in windows or **.config\Dopamine** on Mac and Linux. Dopamine 2 and 3 use the same logic for grouping tracks (combination of Track title and album artist). So I'm really curious to see what is going on.

**Comment by TVJohn56** [comment]
[DopamineDBs.zip](https://github.com/digimezzo/dopamine/files/10956279/DopamineDBs.zip)
I have included the databases for version 2 and 3 which, interestingly, are the same size. The issue isn't exclusive to the Harry Potter books but are particularly noticeable with them as the company that created the MP4 CDs decided to split it into tracks of around 1 minute, so there are literally hundreds of tracks. I can see that it has also happened with one of the Anthony Horowitz books and an episode of Poirot, for instance.
