### ISSUE TITLE
Feature request: ordering the song in the playlist.

### ISSUE THREAD

**Issue by Accout-Personal** [digimezzo/dopamine#393]
I usually order songs in my playlist so when it plays is would play in certain order. Currently it does support drag and drop ordering, but it does not save when the software is closed.

**Comment by cnnn666v2** [comment]
a workaround for that could be just renaming the file names that start with for example a "1", "2", and so on...
Kinda surprised this has been open since 2023 and wasn't implemented yet, as it seems rather easy to do so
