### ISSUE TITLE
Incorrect artist ordering in the "Showcase" and "Now playing" screens

### ISSUE THREAD

**Issue by isicb** [digimezzo/dopamine#43]
My music library is all FLACs, some of which have multiple `ARTIST` tags for songs by multiple artists.
For example "Money Trees" is by Kendrick Lamar _and_ Jay Rock and Anna Wise:
![Edit](https://user-images.githubusercontent.com/67393823/85634024-80060480-b648-11ea-9714-a99271d498ff.png)
Dopamine _correctly_ identifies that such songs are by multiple, _separate_ artists:
![Artists tab](https://user-images.githubusercontent.com/67393823/85634122-b6dc1a80-b648-11ea-8dcb-ceb7a447c29f.png)
However in the "Showcase" and "Now playing" screens, songs' artists are _incorrectly_ listed in _alphabetical_ order...
![Incorrect Showcase](https://user-images.githubusercontent.com/67393823/85634273-04588780-b649-11ea-85f1-84c15be2084c.png)
![Incorrect Now playing](https://user-images.githubusercontent.com/67393823/85634290-0e7a8600-b649-11ea-8bb4-16417ca1a104.png)
...instead of the order they are written in the `ARTIST` tags, as they should be. I have simulated the correct order below:
![Correct Showcase](https://user-images.githubusercontent.com/67393823/85634326-23efb000-b649-11ea-955d-f1b36dddb652.png)
![Correct Now playing](https://user-images.githubusercontent.com/67393823/85634330-26520a00-b649-11ea-89b5-db8de3adf206.png)
This is not correct because a song's artists should be listed by their _level of contribution_ to the song (i.e. the main artist behind a song is listed first, followed by a list of featured artists), as I have written them in my `ARTIST` tags.

**Comment by digimezzo** [comment]
@isicb Nice find! :) I'm probably ordering them alphabetically. I'll have a look.
