### ISSUE TITLE
[BUG] Volume slider UI resets

### ISSUE THREAD

**Issue by BLCK-B** [digimezzo/dopamine#438]
The volume slider UI, not the actual volume, resets to 0 when page changes - after any action from hamburger menu or "now playing".
before and after
![image](https://github.com/digimezzo/dopamine/assets/123077751/b4953791-2deb-4461-a3e1-cee3b6dfeef5)
![image](https://github.com/digimezzo/dopamine/assets/123077751/7dd25365-5b39-4453-aa3c-f4d2d28f6407)

on latest nightly #786, win 11

**Comment by digimezzo** [comment]
@BLCK-B Thanks for reporting this. I'll have a look.

**Comment by Mitia99** [comment]
I can confirm that steps to reproduce the volume slider UI bug are:

1. Play a song
2. Click the album cover (now playing)
![Dopamine_volume slider bug](https://github.com/digimezzo/dopamine/assets/56766778/21316635-d7ed-499b-846e-b11beb9bc54b)
