### ISSUE TITLE
[Suggestion] Drag'n'drop file(s) to play it

### ISSUE THREAD

**Issue by BodoTh** [digimezzo/dopamine#439]
I would love to see (or rather hear) Dopamine play songs that have been thrown via Drag'n'Drop into the app window.
This may either happen by dropping it into bar with the playback control buttons are into the playlist UI (which might be less complicated to do).

Perhaps when dropping into the playback control area you might create a new playlist and then start playing it.

Thanks for this great piece of software.

**Comment by akano12** [comment]
Idk man but double clicking on an audio to play is easier than drag and dropping, doesn't make any sense.
Perhaps you could specify and scenario where this is considered and optimal solution over double clicking?

**Comment by digimezzo** [comment]
@akano12 Actually, the drag and drop has been requested multiple times and makes sense too. Also, @BodoTh's request might concern Dopamine 3, which does not have double-click support yet (that's only in Dopamine 2).

@BodoTh I'll definitely look into that and thanks for loving Dopamine.

**Comment by BodoTh** [comment]
@digimezzo
> I'll definitely look into that and thanks for loving Dopamine.
That would be great

Double click on an mp3 file opens Dopamine and plays the sound? Isn't this what you claim it doesn't yet work in Dopamine 3?
Here it works in D3.

**Comment by digimezzo** [comment]
@BodoTh You're right, double-clicking works. I was convinced I didn't implement that feature yet. I've been too busy with other features since then :)

**Comment by akano12** [comment]
> @BodoTh You're right, double-clicking works. I was convinced I didn't implement that feature yet. I've been too busy with other features since then :)

Been using the AUR version on vanilla arch for a very long time (and even had dopamine before it was added to aur) and dopamine been working as intended.

**Comment by akano12** [comment]
> @akano12 Actually, the drag and drop has been requested multiple times and makes sense too. Also, @BodoTh's request might concern Dopamine 3, which does not have double-click support yet (that's only in Dopamine 2).
> 

Been using the AUR version on vanilla arch for a very long time (and even had dopamine before it was added to aur) and dopamine been working as intended.

**Comment by digimezzo** [comment]
@akano12 That's excellent news! Hello, fellow Arch user :)

**Comment by digimezzo** [comment]
Note to self: https://stackoverflow.com/questions/68104292/how-to-drop-a-file-from-explorer-and-get-its-full-path-to-electronjs-app
