### ISSUE TITLE
Compile Instructions Typo...

### ISSUE THREAD

**Issue by dragonBall561** [digimezzo/dopamine#44]
Hello! I was compiling Dopamine and then I saw something weird in the instructions:

```
cd knowte
```

Was this supposed to be `cd dopamine` or was that correct?

**Comment by digimezzo** [comment]
You're right, that is a copy-paste mistake. I copy pasted the instructions from Knowte.
Be aware though, that compiling Dopamine will, not yet, provide you with a functioning player. Currently, the welcome screen is being built.

**Comment by dragonBall561** [comment]
Yes, but the start screen is working perfectly!
