### ISSUE TITLE
Touchscreen volume slider not working

### ISSUE THREAD

**Issue by Mitia99** [digimezzo/dopamine#446]
**Steps to reproduce**
Control the volume with touchscreen sliding gestures

**Actual behaviour**

![a](https://github.com/digimezzo/dopamine/assets/56766778/232ed2c6-fe60-4e07-bc9b-ad4adc4a38e6)

**Expected behaviour**

![b](https://github.com/digimezzo/dopamine/assets/56766778/7b9f0d5b-33a8-4d90-bc7e-6fa8bcddd392)

**Additional info**
Huawei Matebook E
Latest dopamine nightly preview
Windows 11 22H2 build 22621.2215

Thanks for investigating,

**Comment by digimezzo** [comment]
@Mitia99 Thanks for reporting this. I'll look into it.

**Comment by digimezzo** [comment]
Note to self: check this out https://stackoverflow.com/questions/14887541/touch-screen-and-javascript-dom-mousedown-event

Also check how Angular material slider handles touch events.

**Comment by digimezzo** [comment]
Fixed in 697bf9b3d5e27d74273293032df4cad7cd181dc3
