### ISSUE TITLE
[BUG] Rating column still displayed

### ISSUE THREAD

**Issue by Mitia99** [digimezzo/dopamine#448]
**Steps to reproduce**

1. Browse _Songs_ tab
2. Edit columns
3. Only enable _Artist_ column

![image](https://github.com/digimezzo/dopamine/assets/56766778/6e7bf67d-9052-4e79-b077-7ddbbee9231c)

**BUG**
Rating column still displayed

![image](https://github.com/digimezzo/dopamine/assets/56766778/f13b647f-5add-4f6e-9cf0-bffd3a785e1c)

**Dopamine version**
Latest nightly build

**Comment by digimezzo** [comment]
@Mitia99 Woops. Thanks for reporting!
