### ISSUE TITLE
specific problem: using WinDock by ivanyu causes crash when moving the window

### ISSUE THREAD

**Issue by rSes8** [digimezzo/dopamine#45]
WinDock is an alternative to the native windows feature of docking, moving and adjusting windows in the monitor. A crash, as soon as the window size is changed or it is moved (also with the mouse), can only be detected in Dopamine.

**Comment by digimezzo** [comment]
@rSes8 Could you attach the log file to this issue? You'll find the log file in folder %appdata%\Dopamine\Log
Thank you!

**Comment by rSes8** [comment]
> 
> 
> @rSes8 Could you attach the log file to this issue? You'll find the log file in folder %appdata%\Dopamine\Log
> Thank you!

[Dopamine.log](https://github.com/digimezzo/dopamine/files/4885257/Dopamine.log)

**Comment by digimezzo** [comment]
This is a dopamine-windows issue. I've fixed in. See https://github.com/digimezzo/dopamine-windows/issues/1167
