### ISSUE TITLE
Click the volume icon to mute/unmute

### ISSUE THREAD

**Issue by Mitia99** [digimezzo/dopamine#455]
Dear dev,

It would be great to have the ability to click the volume icon in Dopamine to mute/unmute.

**Expected behaviour**
![Click volume button to mute](https://github.com/digimezzo/dopamine/assets/56766778/96f1e8a7-5f44-47a4-bf81-95a9a6f4f2fa)

**Actual behaviour**
Nothing happens when clicking volume icon in Dopamine.

Thanks,

**Comment by BLCK-B** [comment]
Do you mean the icon in dopamine that doesn't have interaction? I agree.

**Comment by Mitia99** [comment]
> Do you mean the icon in dopamine that doesn't have interaction? I agree.

Yes. Like the volume icon action in Windows Control Center

**Comment by digimezzo** [comment]
Fixed in 2c3d21b6ef229e5917f06e6dfbc2eda607ba2f51

**Comment by Mitia99** [comment]
@digimezzo I think it would make sense to display `Mute` on mouseover to indicate button action like Play, Next, Shuffle etc...
![Screenshot 2023-11-07 104315](https://github.com/digimezzo/dopamine/assets/56766778/d070794a-ada9-4a29-b64a-ace45bae96e7)
