### ISSUE TITLE
Double-clicking song in playlist doesn't play it

### ISSUE THREAD

**Issue by dvoracek-jakub** [digimezzo/dopamine#468]
Double-clicking song in a playlist doesn't play the clicked song. It always plays the first song of the playlist instead. The same behavior applies for list of songs in Folders.

Dopamine  3.0.0 Preview 20

**Comment by Mifault** [comment]
I have the same issue, as well.
Same version as OP.

**Comment by digimezzo** [comment]
That's a known issue in Preview 20. It's fixed in the code and the fix will be in Preview 21.
