### ISSUE TITLE
Artists section includes compilation albums when sorted by "album artist"

### ISSUE THREAD

**Issue by leon14344** [digimezzo/dopamine#47]
Dopamine 2.0.3
Windows 10

I have 3 albums under the name "The Band". For two albums of theirs (The Basement Tapes, and a self-titled album) they are both tagged with their name in the artist and album artist fields as part of standard ID3 tags. However, also appearing under their entry is "Goin' South", a compilation album that has "Various Artists" entered in its Album Artist field. The Band contributes one song to the album, and yet the whole album is listed. This has persisted for several versions of Dopamine, but i've never bothered to submit it. 

It would be preferable to not have the compilation album appear at all when the artist section is sorted by Album Artist, if at all possible.

**Comment by digimezzo** [comment]
@leon14344 Do you mean that the album is listed when clicking on the artist "The Band" or when clicking on "Various artists"?
Would you mind attaching your Dopamine.db to this issue, so I can have a look? You'll find it in folder %appdata%\Dopmamine. Thanks!

**Comment by leon14344** [comment]
@digimezzo It's listed under both, actually. In fact, the "Goin' South" album is listed under every artist that already has an existing entry in the Artists list; I have albums by The Band and The Allman Brothers Band and it appears there, but I don't have anything by .38 Special who appear on "Goin' South" and yet they don't get their own listing, only if I already have other albums. 

Here's the database. I've also link the info for the "Goin' South" album in question so you know what i'm specifically referring to. Worth noting this is happening with other albums under "Various Artists" but what's happening with one is happening to. The discogs info about the album seems to be wrong, so an Amazon link will have to suffice. Thank you

https://www.amazon.com/Goin-South-Various/dp/B000050XUQ


[Dopamine.zip](https://github.com/digimezzo/dopamine/files/4915888/Dopamine.zip)

**Comment by digimezzo** [comment]
@leon14344 Thank you for all this information. I'm checking it out.

**Comment by digimezzo** [comment]
@leon14344 I fixed this issue :) The fix will be in the next release.
