### ISSUE TITLE
Dopamine can't read some songs in my library.

### ISSUE THREAD

**Issue by Mifault** [digimezzo/dopamine#471]
I've noticed that there are songs not showing up in the library at all. I've checked some of them & they were all mp3 files. They only appear when using the 'Folders' tab, but without any information. (example below)
![Screenshot 1](https://github.com/digimezzo/dopamine/assets/107157739/9c970434-1f8e-4ee9-97c6-2f050f1ee760)
The files are played fine in other music players, with all of their information available.
I've also noticed that one of the 3 songs in the image doesn't have the album cover in the app, even though it has one. (example of album art not showing)
![Screenshot 2](https://github.com/digimezzo/dopamine/assets/107157739/1beecfcf-5882-440b-97da-ebf7c89fd972)
Even though this is how the 3 songs appear in my folder & in another player.
![Screenshot 3](https://github.com/digimezzo/dopamine/assets/107157739/33a918d8-3bc7-4b76-b340-55573a6e3ee1)
![Screenshot 4](https://github.com/digimezzo/dopamine/assets/107157739/3654e417-4cc8-4373-bf55-b38a96c97697)

Thank you in advance.

**Comment by digimezzo** [comment]
Could you share one of those files? (if possible) I'd like to test them out. Thank you.

**Comment by Mifault** [comment]
Sure!
The one that Dopamine can't read at all is 'Bigger (remixes)'. The other song that doesn't have the album art show up is 'All Of Your Life (JaySL's Dance Mix)'.
Thank you so much, and if you want more files please let me know.
[Songs error.zip](https://github.com/digimezzo/dopamine/files/13210591/Songs.error.zip)

**Comment by digimezzo** [comment]
This seems to be a problem in node-tag-lib-sharp. I did some debugging but will need help from node-taglib-sharp's creator in order to proceed. I've logged a bug upstream: https://github.com/benrr101/node-taglib-sharp/issues/90
