### ISSUE TITLE
System Notifications (Play/pause key): Contents are wrong (track information missing)

### ISSUE THREAD

**Issue by DevKrishan** [digimezzo/dopamine#48]
Refer image attached with the issue.

I really like the in app notification system when the song changes ,
A possible fix for this could be to show the notification each time the system volume is changed or when we press the volume button.

Else if the Devs would be able to fix the part where it only shows dopamine.exe in the media key handling system notification. It would be flawless. 
![del](https://user-images.githubusercontent.com/15914359/87893540-da369180-ca5d-11ea-8568-b16718ba7399.png)

**Comment by Chealer** [comment]
Please explain how this bug can be reproduced.

**Comment by DevKrishan** [comment]
Hey Philippe,

So in order to reproduce the issue, you simply turn on the "Enable System
Notifications" setting under the Playback settings tab. ( screenshot
attached )

Then when you play any music and try to volume up or down , the "Hardware
Media Key Handling Support by Windows" allows you to
play/pause/next/previous track and volume adjust in this overlay of
notification, which I believe is the System Notification, Instead of the
Dopamine notification.

So
1. The song Title and Artist name is not shown , but the Dopamine.exe alone
is shown.  ( screenshot attached )
2. Album art isn't shown in the system notification.  ( screenshot attached
)
3. [NOT SURE ENTIRELY].The play pause is working properly, but at times the
button doesn't change , i.e it always shows the play button even if the
song is playing.

You can see how it is supposed to work by simply playing a youtube video on
Chrome / A song with album art in Groove Music Player and see what is the
difference.  ( screenshot attached )

Honestly I love the in app notification system, that is dopamine's
notification system , but it only shows up when the track changes, if you
could add a setting under the same options , where we can choose if
pressing the "system volume up or down key" shows the notification, as that
is the most easiest way to interact with the UI, it would be wonderful.  (
screenshot attached )

Really love the new user interface of the app btw , love all the features ,
it's just amazing. Such a lightweight application too, my god. Thanks guys.

Sincerely,
Dev Krishan .R .Purohit
+91 7904241651


[image: image.png]
[image: image.png]
[image: image.png]

[image: image.png]

**Comment by Chealer** [comment]
Thank you @DevKrishan I better understand your problem now. Which Dopamine version do you experience this with?
Your screenshots were not properly joined.

**Comment by DevKrishan** [comment]
> Thank you @DevKrishan I better understand your problem now. Which Dopamine version do you experience this with?

I experienced the issue with the latest build and the 2.0 version too. The screenshots are of the version 2 as I use that because it's a lighter version ( 13 MB on install , when compared to the latest build 69 MB )


> Your screenshots were not properly joined.

Sorry , I attached them in email . Didn't realize it was a github notification  
Hope this helps.
They are in order of how I mentioned 
![image](https://user-images.githubusercontent.com/15914359/88180499-1aa73280-cc4b-11ea-87a8-0bbacf41016c.png)
![image (1)](https://user-images.githubusercontent.com/15914359/88180509-1da22300-cc4b-11ea-9a77-a9ecce825176.png)
![image (2)](https://user-images.githubusercontent.com/15914359/88180515-1f6be680-cc4b-11ea-9c4d-a1b334ecc4d2.png)
![image (2)](https://user-images.githubusercontent.com/15914359/88180522-2135aa00-cc4b-11ea-8a32-847013cb22f3.png)

**Comment by Chealer** [comment]
Thank you
When you write version "2.0", is that 2.0.0? Did you try with 2.0.3?

I suggest to re-title this ticket to "System Notifications (Play/pause key): Contents are wrong (track information missing)".

**Comment by DevKrishan** [comment]
Yes I do mean 2.0.0 & 2.0.3 , sorry for my negligence. 
Also done !
Please do let me know if I can be of any assistance :)

**Comment by Chealer** [comment]
Thank you. I cannot reproduce this (using 2.0.3). The track title, the artist and the album cover show, and "dopamine.exe" does not show.

**Comment by DevKrishan** [comment]
Hey I tried to completely remove 2.0.0 and fresh install 2.0.3 and the issue still persists. 
See screenshots attached below. 
I'll check with a friend of mine too on this and see, but  the issue still persists on my system. 
I have Rainmeter installed and a certain chrome extension that handles the chrome  to system notifications. 

Thank you so much for your time and consideration and I really respect that. Please do wait for me to get back to this thread with the results , I'll try running this on various  platform and troubleshoot and see what is possibly interfering with my notifications.

![image](https://user-images.githubusercontent.com/15914359/88211261-142cb100-cc73-11ea-8166-f80fcb941707.png)

![image](https://user-images.githubusercontent.com/15914359/88211522-72599400-cc73-11ea-82f2-28aad78618ae.png)

![image](https://user-images.githubusercontent.com/15914359/88211548-7b4a6580-cc73-11ea-983b-760a396a4a7a.png)

**Comment by DevKrishan** [comment]
Okay so I turned off that extension in chrome and then instantly it showed me the song details for the dopamine player,
and I turned the extension on again and it still shows me all the relevant information.


So the issue seems to have resolved. Thank you so much for your assistance in this.

**Comment by Chealer** [comment]
There's nothing to thank me about, glad that you solved it quickly.

It may help others if you could name the extension which triggered this problem.

**Comment by DevKrishan** [comment]
WebNowPlaying is the extension name , its used for Rainmeter's Audio visualizer for a interface with chrome and the rain meter skin

To fix the issue I had , just restart the extension and the player in any order. Hopefully it would work.

Thanks Devs !
![image](https://user-images.githubusercontent.com/15914359/88283147-81d6ec80-cd08-11ea-9ff9-affb88e7b077.png)
