### ISSUE TITLE
[Bug] Queue broken

### ISSUE THREAD

**Issue by DopamineUser** [digimezzo/dopamine#490]
Earlier today I upgraded from preview20 to preview21, with a clean reinstall. Now, the playback queue is broken. [Here's a visual explanation](https://github.com/digimezzo/dopamine/assets/148219987/e1661c22-36ad-4f5a-9a64-99c33c6b3c26)

**Comment by digimezzo** [comment]
@DopamineUser Thanks for reporting that. I didn't catch that problem.
