### ISSUE TITLE
[Bug] Windows media control has a double space between artists

### ISSUE THREAD

**Issue by DopamineUser** [digimezzo/dopamine#498]
![image](https://github.com/digimezzo/dopamine/assets/148219987/722dc2cf-4349-4686-ac17-2d91f16bc15c)

Artists were saved like this:
Artist1; Artist2
The space between should be ignored like in dopamine, but media control makes it part of the artist.

**Comment by digimezzo** [comment]
@DopamineUser Thank you for reporting this. Really a nice catch!
