### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Nickiel12** [digimezzo/dopamine#5]
What are the different scripts for running this? And is it "working" because when I run _npm _start__ it comes up with a similar startup window as to that of windows, but when setup is done all it says is "collection works."

**Comment by digimezzo** [comment]
@Nickiel12 You're doing it right. There is, at this point, nothing else that works. It is still in very early development.

**Comment by Nickiel12** [comment]
Thank you! I am currently enjoying your windows version, and was just checking out your other projects.

**Comment by digimezzo** [comment]
@Nickiel12 Thanks for the interest. I'm finalizing Dopamine 2.0. It's release is imminent. After that, my main focus goes tot version 3.0, which is the code in this repository.
