### ISSUE TITLE
[Bug] Playback is always shuffled

### ISSUE THREAD

**Issue by Parzival5129** [digimezzo/dopamine#501]
Since the last update, my songs are always being played in shuffle, no matter the actual setting.

**Comment by digimezzo** [comment]
@Parzival5129 That should be fixed in Preview 22. Could you test and confirm? Thank you.

**Comment by Parzival5129** [comment]
@digimezzo Works fine now! Thx

**Comment by digimezzo** [comment]
@Parzival5129 Thank you for confirming. I'm closing this issue.
