### ISSUE TITLE
[Bug] Selecting multiple tracks to play only plays one of them, ignores the rest instead of adding them to the queue

### ISSUE THREAD

**Issue by DopamineUser** [digimezzo/dopamine#505]
![image](https://github.com/digimezzo/dopamine/assets/148219987/76173e0c-2d16-44c8-8075-eecd5b104e52)
Drag and drop works but opening like this doesn't work

**Comment by digimezzo** [comment]
This seems to happen on Windows, but not on Linux. On Linux, all files are queued. Not sure yet how to solve this. This article might give some pointers: https://stackoverflow.com/questions/62766392/how-to-open-a-file-through-open-with-in-an-already-running-electron-app

**Comment by digimezzo** [comment]
Fixed in 38775861200a5c87f9629210acd83dc18e22fb1d
