### ISSUE TITLE
issue running npm install on pop os 20.04

### ISSUE THREAD

**Issue by stnm12brX2** [digimezzo/dopamine#51]
weirdly enough, I can run npm run rebuild-sqlite and It successfully rebuilds...
here is the text that the command prints, I have no idea how to install peer dependencies.

meee@pop-os:~/dopamine$ npm install

> Dopamine@3.0.0-preview.1 postinstall /home/sempai/dopamine
> npm run postinstall:electron && electron-builder install-app-deps

> Dopamine@3.0.0-preview.1 postinstall:electron /home/sempai/dopamine
> node postinstall

  • electron-builder  version=22.5.1
  • loaded configuration  file=/home/sempai/dopamine/electron-builder.json
  • rebuilding native dependencies  dependencies=better-sqlite3@7.1.0 platform=linux arch=x64
  • install prebuilt binary  name=better-sqlite3 version=7.1.0 platform=linux arch=x64
  • build native dependency from sources  name=better-sqlite3
                                          version=7.1.0
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.5
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ /home/sempai/.npm/_prebuilds/6fca5e-better-sqlite3-v7.1.0-electron-v69-linux-x64.tar.gz
    prebuild-install http request GET https://github.com/JoshuaWise/better-sqlite3/releases/download/v7.1.0/better-sqlite3-v7.1.0-electron-v69-linux-x64.tar.gz
    prebuild-install http 404 https://github.com/JoshuaWise/better-sqlite3/releases/download/v7.1.0/better-sqlite3-v7.1.0-electron-v69-linux-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=4.2.12 runtime=electron arch=x64 libc= platform=linux)
    
npm WARN @angular-devkit/build-angular@0.1000.4 requires a peer of @angular/compiler-cli@>=10.0.0-next.0 < 11 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/build-angular@0.1000.4 requires a peer of typescript@>=3.9 < 3.10 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/animations@8.2.14 requires a peer of @angular/core@8.2.14 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@10.0.4 requires a peer of @angular/compiler-cli@>=10.0.0-next.0 < 11 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@10.0.4 requires a peer of typescript@>=3.9 < 3.10 but none is installed. You must install peer dependencies yourself.

audited 2305 packages in 64.891s

92 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

sempai@pop-os:~/dopamine$ npm install -g install-peerdeps
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN checkPermissions Missing write access to /usr/local/lib
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sempai/.npm/_logs/2020-07-26T22_08_49_744Z-debug.log
sempai@pop-os:~/dopamine$ sudo npm install -g install-peerdeps
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/install-peerdeps -> /usr/local/lib/node_modules/install-peerdeps/lib/cli.js

> core-js@2.6.11 postinstall /usr/local/lib/node_modules/install-peerdeps/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

----------then i tried npm install -- force and the same stuff printed as npm install.

**Comment by stnm12brX2** [comment]
forgot to add, sudo npm install -g install-peerdeps didn't work either.

**Comment by digimezzo** [comment]
@stnm12brX2 This seems to be a permissions issue. npm is probably trying to install global packages, which reside in /usr/local/lib/node_modules, but your user doesn't have the required permissions to do so. Some people suggest to give to make your user the owner of /usr/local/lib, but I'm not sure that is a good solution. Please have a look at this page https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

This is the official npm documentation concerning such issues.
