### ISSUE TITLE
'songs' string isn't available for translation

### ISSUE THREAD

**Issue by adem4ik** [digimezzo/dopamine#519]
Version: v3.0.0-preview21

1. Switch to any other language (i.e. Russian or Chinese Simplified)
2. Open **Songs** tab

Result: `<number> songs` isn't translatable.

![изображение](https://github.com/digimezzo/dopamine/assets/4707112/76eeaca5-4e62-4b8e-8f9f-56264e4c9aa7)

**Comment by digimezzo** [comment]
That was fixed in Preview 22
