### ISSUE TITLE
[Bug] Lyrics page display issues

### ISSUE THREAD

**Issue by DopamineUser** [digimezzo/dopamine#521]
the cover has a shadow outline next to it and the track name does not format properly, going over the lyrics depending on the length
![image](https://github.com/digimezzo/dopamine/assets/148219987/e6db3fe8-6dee-4096-aff0-d91dba296b8e)

**Comment by digimezzo** [comment]
Thanks for reporting this. It was already known, and fixed in dd39c94. Preview 22 will have the fix.
