### ISSUE TITLE
Dopamine nightly-win no music found

### ISSUE THREAD

**Issue by BLCK-B** [digimezzo/dopamine#528]
Latest Nightly builds #917 windows build does not see any music. Reinstallation, adding folders did not solve it.
![image](https://github.com/digimezzo/dopamine/assets/123077751/c2ed63e0-8f7c-4483-8af3-12ffb0be1fc7)

**Comment by digimezzo** [comment]
What are the logs saying? Could you attach the log file here? You'll find it like this:

![image](https://github.com/digimezzo/dopamine/assets/11945339/3a7dcfee-9efe-44f9-b24d-60ba24638d78)

**Comment by BLCK-B** [comment]
[Dopamine.log](https://github.com/digimezzo/dopamine/files/13755327/Dopamine.log)

**Comment by digimezzo** [comment]
Are these checkboxes checked?

![image](https://github.com/digimezzo/dopamine/assets/11945339/294deb64-c1dc-4d84-8d64-d231872219e6)

**Comment by BLCK-B** [comment]
Now they are. No music shown.
[Dopamine.log](https://github.com/digimezzo/dopamine/files/13758391/Dopamine.log)

**Comment by digimezzo** [comment]
Could you share your Dopamine.db? Indexing errors are sometimes also logged in there.

**Comment by BLCK-B** [comment]
![ezgif-2-3a11d1d5d9](https://github.com/digimezzo/dopamine/assets/123077751/d2fd9287-7387-4754-ba1f-443413bb5fa9)
[DopamineDB.zip](https://github.com/digimezzo/dopamine/files/13766342/DopamineDB.zip)

**Comment by digimezzo** [comment]
@BLCK-B Thank you for the video! That's very helpful. There seems to be a bug in loading the songs when not all screens are shown. I'm scheduling to fix it for preview 22.
