### ISSUE TITLE
Not getting Synced Lyrics

### ISSUE THREAD

**Issue by FrozenCoder1** [digimezzo/dopamine#53]
![Annotation 2020-07-28 160310](https://user-images.githubusercontent.com/66153345/88655069-da80fd80-d0eb-11ea-9d57-330530896949.png)

**Comment by FrozenCoder1** [comment]
Please can anyone add Musixmatch Support to it?

**Comment by digimezzo** [comment]
@FrozenCoder1 Musixmatch is a paid service. It will, unfortunately, not be possible to use it in Dopamine.
