### ISSUE TITLE
Uninstalling dopamine should delete the AppData/Roaming/Dopamine and AppData/Local/dopamine-updater folders

### ISSUE THREAD

**Issue by DopamineUser** [digimezzo/dopamine#534]
and for some strange reason, i have to restart my pc after deleting all dopamine files before installing it again in order to have it start fresh, else it loads everything back somehow???

**Comment by DopamineUser** [comment]
I've seen programs add a checkbox to the uninstaller to erase configurations or everything, that would be great.

**Comment by digimezzo** [comment]
@DopamineUser That should be possible. I'm adding this link to assist myself during development: https://medium.com/@mohitkaushal91/how-to-build-package-and-distribute-your-cross-platform-desktop-apps-electron-builder-935ed44d40d1

I'll try to provide that in preview 23, which I'll release in a few days.
