### ISSUE TITLE
[Bug] Playback Queue showing only 5 tracks

### ISSUE THREAD

**Issue by DopamineUser** [digimezzo/dopamine#538]
i can scroll it but it only shows 5 tracks max
![image](https://github.com/digimezzo/dopamine/assets/148219987/a39bd21e-a47e-42bb-b30b-30d5d5082af6)
![image](https://github.com/digimezzo/dopamine/assets/148219987/27e3c17a-52ab-4c10-b655-50e77ace1d92)

**Comment by digimezzo** [comment]
Ugh, this nasty bug. It appeared during preview 22 development and I thought I fixed it. Apparently not :(
