### ISSUE TITLE
[Bug] Low res album covers since Preview 22

### ISSUE THREAD

**Issue by Parzival5129** [digimezzo/dopamine#542]
All album covers in the "full screen mode" appear to have a very low resolution since the last update despite the actual dimensions of the cover files

**Comment by digimezzo** [comment]
@Parzival5129 Could you send a screenshot of what you mean? I did set a maximum size to the cover art on the now playing screens, for performance reasons. Maybe that's what this is about.

**Comment by Parzival5129** [comment]
@digimezzo Well, I have a 43" 4k screen so I might notice it more than others? Anyway [here's](https://imgur.com/a/nfyjHPa) a link to a png screenshot. I measured the screen size of the cover window and its about 980x980px that shouldn't be larger than your max. size, right?

**Comment by digimezzo** [comment]
@Parzival5129 I maxed it at 500x500px. But seeing your situation I now realize that wasn't a good idea. I'll undo that change in the next preview.
