### ISSUE TITLE
[Enhancement] Dynamic Colors

### ISSUE THREAD

**Issue by DavidRLTG** [digimezzo/dopamine#551]
![image](https://github.com/digimezzo/dopamine/assets/87834635/17a0525b-dc9b-45d9-8e30-7bb3cceea5ad)

Image attached, An example of how it could look via the Beats theme and a fitting song.

I think it would be really cool if the app colors changed depending on the album cover of the song playing.
Makes it more immersive, I guess.

**Comment by digimezzo** [comment]
@DavidRLTG That's a great idea! I'm adding this as a feature request. Oh by the way, I see in your screenshot that the scroll bars are blue, despite setting the Beats theme. That's a know issue. I made a small mistake in the last preview. This will be fixed in the next preview.

**Comment by DavidRLTG** [comment]
Thanks fella :)
And aye, good luck with fixing the issue!!

**Comment by TheBeeBoi** [comment]
+1

**Comment by TheBeeBoi** [comment]
I might make a PR

**Comment by digimezzo** [comment]
@TheBeeBoi Sounds great! I'm not working on this feature yet, so feel free to create a PR. I'll gladly review it.
