### ISSUE TITLE
saving playback position

### ISSUE THREAD

**Issue by neomag** [digimezzo/dopamine#559]
Dopamine does not save playback position in playlist
This creates inconvenience when listening  audiobooks

how to reproduce:
select not the first track in the playlist
shut down dopamine
open - playback will start from the first track

**Comment by Trethien** [comment]
I created a Github account just so I could second this.  :)

I've used Dopamine 2 for years and the only thing stopping me using Dopamine 3 full time is having to start over each time I start the player.  I tend to have specific music on in the background while I work, so it's nice to go straight back into my playlist without having to find it again.

(I switched from Windows to Linux recently, hence me not being able to use Dopamine 2 any more)

**Comment by digimezzo** [comment]
Fixed with #630

**Comment by Trethien** [comment]
Excellent update, thank you.  :)

**Comment by digimezzo** [comment]
You're welcome 😁
