### ISSUE TITLE
failing to find a file that has multiple hashtags in directory

### ISSUE THREAD

**Issue by katelyynn** [digimezzo/dopamine#565]
i have a bit of a strange music organisation i suppose that looks like this:
![image](https://github.com/digimezzo/dopamine/assets/46572320/9ded29f4-98f3-4e0c-80c4-345e458907ac)

but whenever i try to play a file in said directory i get an error saying its not found:
![image](https://github.com/digimezzo/dopamine/assets/46572320/7980ce05-e3fe-4d49-8433-e124507d0e77)
the directory in file explorer:
`K:\home\music\Juice WRLD\# UNRELEASED\# LATEST COMP\2. Sessions (Stems&Edits)\Session Edits\734 (Sessions).mp3`

which seems to be as it's parsing the first # correctly (%23).. but not the 2nd?
![image](https://github.com/digimezzo/dopamine/assets/46572320/df09c0b6-faf5-43b0-87da-25e2cb246e1f)

just my best guess as if i copy the address into a browser and swap out the 2nd # with a %23 it plays just fine

---

here's the log if its needed, it doesnt seem to have anything at all relevant tho :3 
[Dopamine.log](https://github.com/digimezzo/dopamine/files/14154614/Dopamine.log)

**Comment by digimezzo** [comment]
@katelyynn Thanks for reporting this. There is logic to replace # by %23, but unfortunately, I made a mistake and it only replaces the first # as you correctly found out. I'll fix this in the next preview.

**Comment by katelyynn** [comment]
thanks!!
