### ISSUE TITLE
[Bug] Constant library refreshing

### ISSUE THREAD

**Issue by Parzival5129** [digimezzo/dopamine#576]
Okay first of all the new UI (especially the settings) looks sick.
Only issue I noticed so far is the library refresh doesn't stop anymore after a while.

**Comment by digimezzo** [comment]
@Parzival5129 Could you attach the log file(s) to this issue? You might have to zip them to be able to drag and drop them here.

**Comment by Parzival5129** [comment]
> @Parzival5129 Could you attach the log file(s) to this issue? You might have to zip them to be able to drag and drop them here.

Sure, here it is:
[Dopamine.log](https://github.com/digimezzo/dopamine/files/14395735/Dopamine.log)

**Comment by digimezzo** [comment]
@Parzival5129 Thanks. Could you also tell me what you mean with constant refreshing? Is it just ever ever startup or continuously? What message do you see from Dopamine? Could you attach a screenshot?

**Comment by Parzival5129** [comment]
@digimezzo It continuously shows this message and consumes a lot of CPU performance
![image](https://github.com/digimezzo/dopamine/assets/94785975/59020ca1-7401-419f-bfe5-d94747d48e68)

**Comment by digimezzo** [comment]
@Parzival5129 Thank you. I think the refreshing is getting stuck on the album art. In the logs I see that track indexing finishes at some point, but album artwork updating does not. I'm trying to figure out why.

**Comment by digimezzo** [comment]
Related to #577

**Comment by digimezzo** [comment]
Fixed in preview 25.
