### ISSUE TITLE
[Bug] Very Poor Performance

### ISSUE THREAD

**Issue by DopamineUser** [digimezzo/dopamine#577]
Ever since updating to preview24, dopamine is very very slow and taking up to 28% CPU (Intel i5) when im interacting with it, and around 13% when its minimized (the visualizer is disabled).

Also, when dopamine's window is in focus, my PC stops going into screen saver mode, which wasn't the case before this update.

> [error] [AlbumArtworkCache] [addArtworkDataToCacheAsync]  Could not add artwork data to cache. Error: maxMemoryUsageInMB limit exceeded by at least 37MB

also noticed this in the logs

**Comment by HilloBerries** [comment]
Same here

**Comment by Patrock404** [comment]
I've also noticed this, I switched back to preview 23.

**Comment by digimezzo** [comment]
Could you all add your logs to this issue?

**Comment by DopamineUser** [comment]
> Is performance also bad when you disable refreshing of collection in the settings and restart dopamine?

That fixed it

**Comment by digimezzo** [comment]
@DopamineUser Thank you for testing that out. I made big changes to the indexer and wanted to know if the performance issues were related to that. Could you also attach your full log to this issue? I want to undertand in indexing gets stuck on your system. As it is not happening on my computer. Thanks.

**Comment by Crocodile73** [comment]
Same issues for me. Disabling automatic refresh help performance. But its stuck on updating album covers. Has no covers for any.

**Comment by digimezzo** [comment]
Note to self: this coudl be a "Jimp" issue. See: https://github.com/jimp-dev/jimp/issues/915

**Comment by DopamineUser** [comment]
> @DopamineUser Thank you for testing that out. I made big changes to the indexer and wanted to know if the performance issues were related to that. Could you also attach your full log to this issue? I want to undertand if indexing gets stuck on your system. As it is not happening on my computer. Thanks.
[Dopamine.log](https://github.com/digimezzo/dopamine/files/14405147/Dopamine.log)

**Comment by Pelintra81** [comment]
I also have poor performance since the last update. Turning off collection automatically refresh doesn't help.

**Comment by digimezzo** [comment]
@Pelintra81 @DopamineUser @Crocodile73 @HilloBerries @Patrock404 

Could you try the latest nightly which is here: https://github.com/digimezzo/dopamine/actions/runs/8107139535

That's essentially a release candidate for preview 25. It should fix the performance issues. Please let me know if it solves your issues.

**Comment by DopamineUser** [comment]
> Could you try the latest nightly which is here: https://github.com/digimezzo/dopamine/actions/runs/8107139535

everything works properly now, and .tiff images work.

**Comment by Crocodile73** [comment]
Everything is running fine for me also now.

**Comment by HilloBerries** [comment]
> @Pelintra81 @DopamineUser @Crocodile73 @HilloBerries @Patrock404
> 
> Could you try the latest nightly which is here: https://github.com/digimezzo/dopamine/actions/runs/8107139535
> 
> That's essentially a release candidate for preview 25. It should fix the performance issues. Please let me know if it solves your issues.

Yes, this fixes it for me. Runs very smooth now.

**Comment by digimezzo** [comment]
Thanks all for testing out the nightly!

**Comment by Pelintra81** [comment]
It's working fine here now, thank you!

**Comment by DopamineUser** [comment]
> everything works properly now, and .tiff images work.

actually, .tiff covers only display on the "pages", not the now playing screen or the playing bar
