### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'webContents') during application shutdown

### ISSUE THREAD

**Issue by moopet** [digimezzo/dopamine#582]
I saw this error box when closing the application. It was refreshing the collection in the background at the time, but I was in the albums view before I clicked the close-window icon.

![image](https://github.com/digimezzo/dopamine/assets/242921/c18271ee-f9e9-4438-a114-298de8dda20b)

I have _not_ been able to replicate this, but thought it was still worth sharing.

OS: Windows 11
App version: preview-23

**Comment by digimezzo** [comment]
@moopet Thank you for reporting this.

**Comment by havocera** [comment]
I have also encountered this situation recently. How did you solve it? Please help. Thank you.

**Comment by havocera** [comment]
> I have also encountered this situation recently. How did you solve it? Please help. Thank you.

![Uploading 微信图片_20240627222012.jpg…]()
