### ISSUE TITLE
Make Button Foreground Colors Theme-able

### ISSUE THREAD

**Issue by dermeck** [digimezzo/dopamine#583]
There are a few places where the background of elements is affected by the color theme but the foreground is not. This makes some things hard to read, when light primary/secondary colors are configured and the foreground is hard coded to white.

One example is the artist header, but there are a few places where:
`background: linear-gradient(45deg, var(--theme-primary-color) 30%, var(--theme-secondary-color) 100%);` or `background: var(--theme-accent-color);` is set in combination with `color: white`.

I'd be happy to tackle it if you want. I'm not sure if every case should get its own variable or if it's `primary-button-text`. I'd probably go with one new variable `highlight-text-color`.

**Comment by digimezzo** [comment]
@dermeck Thank you for reporting this. It makes sense to have this color in a new variable. Feel free to create a pull request. I'll gladly review it.

**Comment by dermeck** [comment]
@digimezzo the related PR is here: https://github.com/digimezzo/dopamine/pull/585
