### ISSUE TITLE
Genres Tab search doesn't work (Linux Version)

### ISSUE THREAD

**Issue by i34sti1337** [digimezzo/dopamine#584]
When I go to the tab "Genres" and write a genre into the search bar he shows me the genres that are available on the left side, but when I click on the genre neither the album or the tracks are popping up in comparison to the working (Artists/Albums/Songs) Tabs. Same is true for the Playlists Tab

![Screenshot 2024-03-03 at 12-41-31 2024-03-03-124047_2560x1440_scrot png (PNG Image 2560 × 1440 pixels) — Scaled (87%)](https://github.com/digimezzo/dopamine/assets/112108718/3e05b26f-ff4d-4042-850d-95a21899f6a6)

**Comment by DopamineUser** [comment]
that's because you searched for songs called "Melodic Hardcore", the search bar isn't for filtering genres but song names

**Comment by digimezzo** [comment]
@DopamineUser Actually, the search bar is for filtering on all items which are on the selected screen. So this is indeed a bug. Thanks @i34sti1337 for reporting it. I'll plan it for the next preview.

**Comment by digimezzo** [comment]
@DopamineUser The screen should still show the items which are under the "Melodic hardcore" genre. I need to have a closer look but I think this is indeed a bug. Thanks for reporting this @i34sti1337.

**Comment by dermeck** [comment]
@digimezzo this PR should fix the issue: https://github.com/digimezzo/dopamine/pull/596
