### ISSUE TITLE
Pressing 'Space' key when editing Playlist toggles play

### ISSUE THREAD

**Issue by dermeck** [digimezzo/dopamine#589]
Pressing Space while Creating/Editing Playlist and Playlist Folders should not toggle the play/pause.

I'd be happy to tackle this. There seems to be a check for `isInputDialogOpened` missing. Although I suggest to check for the input target instead (prevent keyboard controlling the player whenever an input is the target).

**Comment by digimezzo** [comment]
@dermeck Please do. I'm open for help on this matter :)
