### ISSUE TITLE
Rich Presence to discord

### ISSUE THREAD

**Issue by lucassshw** [digimezzo/dopamine#6]
It would be interesting to show in the discord the name of the song, the album and the artist currently playing.

**Comment by NetboxMiner** [comment]
I agree with this one. I run a game server and do custom maps for it. I always have players asking what music I am listening to while I am map making and it would really be awesome to share that via a bot linking it to my name. Plus I think this could be good for Dopamine....have it say Listening with Dopamine, then track and artist...good advertising for you guys

**Comment by digimezzo** [comment]
Dopamine 2 and 3 now have this functionality.

**Comment by navidmafi** [comment]
It would be great to add an option to enable or disable this feature.
This can be an option in settings, or something like Spotify's "Private session"

**Comment by digimezzo** [comment]
> It would be great to add an option to enable or disable this feature.
> This can be an option in settings, or something like Spotify's "Private session"

There is already such option in the **Settings > Online** tab

**Comment by navidmafi** [comment]
Oh, sorry, I didn't even see there were tabs for settings
Thanks
