### ISSUE TITLE
Issue with moving tracks inside playlists

### ISSUE THREAD

**Issue by GitSaus** [digimezzo/dopamine#617]
## I'm submitting a complaint about the playlists part of the app

<pre><code>
[ ] Regression 
[ ] Bug report  
[ ] Feature request
</code></pre>

 Moving songs in playlists either doesn't move them or flings them at random distance in the tracklist

## I'm using these versions

* Windows version: Windows 11
* Dopamine version: 3.3.0-preview.23

## Reproduction steps

* Step 1 Add a good bunch of songs in a playlist
* Step 2 Move them around

## Log file

https://github.com/digimezzo/dopamine-windows/assets/157875183/94d7f558-8974-4ab3-94c4-174074cf823e

**Comment by digimezzo** [comment]
Fixed with #393
