### ISSUE TITLE
playback controls aren't kept after restarting the app

### ISSUE THREAD

**Issue by 0error7** [digimezzo/dopamine#619]
I love dopamine and I use it since almost 2 years now
but everytime I restart the app, the loop all and the shuffle buttons are reseted to their default state, so no loop and no suffle

**Comment by digimezzo** [comment]
@0error7 Thanks for reporting this. I'm planning this for the next preview.

**Comment by 0error7** [comment]
Thank you a lot!

**Comment by DopamineUser** [comment]
actually this should be an option, to keep or not to keep the playback control settings.

**Comment by 0error7** [comment]
yeah I agree, we will see how this option will come along in the next preview then!

**Comment by digimezzo** [comment]
@0error7 and @DopamineUser Agree with both of you. Sorry I couldn't get it into the just released preview 27. It is currently planned for preview 28.

**Comment by 0error7** [comment]
no worry! as long as it is implemented one day or another, I don't really care!
take your time!
this is not a paid software and I think this is normal to wait a bit for our requested features to be added in the app
