### ISSUE TITLE
how it that , that i can't sort by date added just like any other player ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [digimezzo/dopamine#62]
just like this 
![image](https://user-images.githubusercontent.com/20546638/89919176-3aeb6100-dbfb-11ea-9ddc-35e0802fa418.png)

**Comment by digimezzo** [comment]
@minanagehsalalma Because on that screen, sorting is done by clicking on the column headers. Add the 'Date added' column and sort by it. You can add colums by right clicking on the songs list and choosing 'Columns...'

**Comment by minanagehsalalma** [comment]
> @minanagehsalalma Because on that screen, sorting is done by clicking on the column headers. Add the 'Date added' column and sort by it. You can add colums by right clicking on the songs list and choosing 'Columns...'

thanks , sorry for bothering you :)

**Comment by digimezzo** [comment]
> 
> 
> > @minanagehsalalma Because on that screen, sorting is done by clicking on the column headers. Add the 'Date added' column and sort by it. You can add colums by right clicking on the songs list and choosing 'Columns...'
> 
> thanks , sorry for bothering you :)

You're welcome! :)
