### ISSUE TITLE
Rating requires double click to save correct

### ISSUE THREAD

**Issue by Tiypoh** [digimezzo/dopamine#622]
When rating music with save to file turned on, it requires you clicking it, then clicking it again so it clears the rating, then clicking it again to get a correct file rating, otherwise it will only be a 1 star on the file and upon reloading the software it shows as 2 stars, with both of those values no matter what rating you click. Also upon clicking again to clear the rating, it appears to leave it the same on the file.

**Comment by digimezzo** [comment]
@Tiypoh Which preview are you on? This seems to have been fixed in preview 25. See: https://github.com/digimezzo/dopamine/issues/555

**Comment by Tiypoh** [comment]
@digimezzo i noticed it on preview 27 I think, Im on 29 now and it just happened, although Ill note it only seems to happen if the song hasnt been rated before, so if I change the rating on a song I've already rated it works fine, but every time if its never been rated it goes to 1 star no matter what. See attached screenshot below. I'll download the latest and recheck right now.
![image](https://github.com/user-attachments/assets/ca8edddf-86f9-45c7-82f7-28eebe0b19b4)

**Comment by Tiypoh** [comment]
Yep just tried it on preview 31 and its still there. Been loving the app otherwise though man very nice job, everything a music player needs to be, nothing more or less, and unlike other ones it looks good too.

**Comment by Tiypoh** [comment]
Just as an idea as a hobby coder myself, perhaps when a rating is selected you could check to see if its equal to 0, and if so simply set the rating twice. I tried digging through the code to fix it myself, I think you can just change line 141 in dopamine/src/app/ui/components/rating
/rating.component.spec.ts to
`             trackRepositoryMock.verify((x) => x.updateRating(track.id, track.rating), Times.twice());`
I think that would be a quick dirty fix for now but I could be wrong, I've never really worked with js or ts before.
