### ISSUE TITLE
[Feature] Better Artist grouping

### ISSUE THREAD

**Issue by Readf0x** [digimezzo/dopamine#625]
The most common way for songs to be tagged is to group multiple artists into one (usually for the purpose of backwards compatibility with older devices) 
![image](https://github.com/user-attachments/assets/39189dc4-ff90-4c33-8ede-fbb4261d45b6)
But reading the artist line with zero filtering leads to annoyingly having a ton of extra artists in the artist tab (and the songs with features not appearing in the actual artist's tab).
Now, this is expected behavior, but automatically filtering the artist lines by splitting it at features (`'feat.'`, `'ft.'`, `'&'`, etc.) would be a great quality of life feature.

**Comment by digimezzo** [comment]
I like the idea and will verify if this can be done.

**Comment by Readf0x** [comment]
After some more thinking, I realized there are some artists with an ampersand in their names, so the logic might end up a little more complex than expected.

**Comment by digimezzo** [comment]
@Readf0x Indeed, I hadn't thought of that. It's not possible to have this work correctly in a fully automated way. The only way I see to add the feature is to provide these options for the user:

1. Toggle (on or off) split on texts
2. Customizable list of texts to split on, with 'ft.', 'feat.' as default for example
3. Customizable list of exclusions (a list of artists to never split)

Could that work? If you have any other ideas, everything is welcome 😁

**Comment by Readf0x** [comment]
@digimezzo That sounds like a perfect solution! I think the exclusions list should work something like, "If this specific substring is found, do not split anything within it." That way if there are any features on any of those artist's tracks, it will still work as intended.
