### ISSUE TITLE
[Bug] Album song list order can't be sorted numerically

### ISSUE THREAD

**Issue by Danielshmaniel** [digimezzo/dopamine#628]
Most albums, despite having the correct song numbers do not show in ascending order like normal, instead the numbered songs are "shuffled" throughout the playlist (despite shuffle not being turned on).
I tried removing the album from the music directory, putting it back in and refreshing Dopamine, but it's still the same.
Edit: Other sorting such as alphabetically is possible, just not numerically.

**Comment by digimezzo** [comment]
@Danielshmaniel Could you show a screenshot of this? Also, which preview are you using?

**Comment by Danielshmaniel** [comment]
@digimezzo 
![image](https://github.com/user-attachments/assets/f3ee2cce-58ad-4c86-b5af-0f4de37846a5)
here's an example. the preview version is: 3.0.0-preview.19
