### ISSUE TITLE
Lack of Bit-Perfect Audio. (Lower Resampling rate) 

### ISSUE THREAD

**Issue by FrozenCoder1** [digimezzo/dopamine#63]
Dopamine is a great music player and also the best ever I've listened to...
But I am Disappointed a bit after seeing this...
I hope this must be fixed soon...

![85225987-8e041d00-b3dd-11ea-96e0-eb28f7fd9c0d](https://user-images.githubusercontent.com/66153345/90309709-79896000-df08-11ea-9c3d-25a24dfd1af1.png)

**Comment by FrozenCoder1** [comment]
HI, Bro (Raphaël).
Can please add this as a bug...?

**Comment by digimezzo** [comment]
@FrozenCoder1 I forgot this was in there. Thanks for pointing it out. I've logged this issue in the dopamine-windows repository: https://github.com/digimezzo/dopamine-windows/issues/1187
The "dopamine" repository is for Dopamine 3. That is currently not so clear. I'll try to make it more clear.

**Comment by digimezzo** [comment]
Th bug is fixed in https://github.com/digimezzo/dopamine-windows/commit/de16848aec224e943a9bee03f434282c65a83f1d
