### ISSUE TITLE
[Feature Request] Queue Retention after software exit

### ISSUE THREAD

**Issue by GLADE3** [digimezzo/dopamine#630]
Hello, been jumping a few players and trying this one.

One major QoL feature I'm missing is queue retention, where the queue playing is preserved even if the software closes down. Sometimes I queue a few hours of albums at a time, and it's unfortunate that when I try to return to the queue after pausing, the software has frozen and I have to exit.

The queue is then lost after re-opening.

Thanks and regards.

Edit: I see that a similar feature is intended on 3.0 release, but only for last played song, not the entire queue.

**Comment by digimezzo** [comment]
@GLADE3 I'll add this in preview 29.
