### ISSUE TITLE
Error - It won't start

### ISSUE THREAD

**Issue by trifon81** [digimezzo/dopamine#650]
After the update of August 5 (Dopamine 3.0 Preview 30), the player does not start. The operating system is Mac OS.
![Screenshot 2024-08-08 at 22 17 26](https://github.com/user-attachments/assets/5274218d-b1f1-4eac-bf84-bc371385074e)

https://mega.nz/file/4d0BgBxK#GncEzgKp71Di2axifsKrwhkyhMlVaOBpY6n0nVEymps

**Comment by digimezzo** [comment]
@trifon81 Could you try to start it via the terminal, to see if there are any error messages popping up?

**Comment by digimezzo** [comment]
Fixed in 16964a1d221bda5958b6db68b524ca7f98d95e6d

**Comment by trifon81** [comment]
> @trifon81 Could you try to start it via the terminal, to see if there are any error messages popping up? Just open a terminal window and type "dopamine" (without the quotes). Thanks.
> 
> Edit: never mind that, I found the problem. A mistake in the Bulgarian translation file makes the application crash. I'll fix that today and release preview 31 with the fix. Thank you for logging this bug.

In my translation, it was the problem. I don't know where I went wrong. I'm sorry! :)

**Comment by digimezzo** [comment]
@trifon81 It was a missing comma on line 270 :)

**Comment by trifon81** [comment]
> @trifon81 It was a missing comma on line 270 :)

A small thing, but it ruins the whole program.

**Comment by digimezzo** [comment]
yes, that should not cause an application crash though. I've created this issue #651 to investigate if I can improve that.
