### ISSUE TITLE
Does not play double-clicked files on Mac

### ISSUE THREAD

**Issue by trifon81** [digimezzo/dopamine#656]
If I want to open a file that is not in the library by double clicking it does not start.  Only by dragging from the folder into the player it is played.

**Comment by trifon81** [comment]
The problem is not solved. Here's what happens: https://mega.nz/file/FVl3WYDB#HKE2eui8t3mSpSU_Uca98nZi3miO7V8UK3Vn-S0iw7k

**Comment by digimezzo** [comment]
@trifon81 Thanks for the video. This problem seems to be limited to Mac. I'll try to solve that in the next preview.

**Comment by digimezzo** [comment]
@trifon81 Could you try to reproduce the problem once more and after that, send me the log file? You'll find the log by going to Advanced > Log file and clicking on "View log":
![image](https://github.com/user-attachments/assets/b3b52344-2f60-4cec-8060-aa443dc737c8)

**Comment by trifon81** [comment]
@digimezzo https://mega.nz/file/1N912KKL#BCVNbQM2wkc1eY-zwdWtIRSQNf0Gt-yXBTHVITlHVpI

**Comment by digimezzo** [comment]
Note to self, for Mac we might have to do something different: https://stackoverflow.com/questions/50935292/argv1-returns-unexpected-value-when-i-open-a-file-on-double-click-in-electron

**Comment by trifon81** [comment]
> Note to self, for Mac we might have to do something different: https://stackoverflow.com/questions/50935292/argv1-returns-unexpected-value-when-i-open-a-file-on-double-click-in-electron

Unfortunately, I'm not good at these codes and I don't know how to do it.

**Comment by trifon81** [comment]
Maybe if you write the exact code that I just enter in the terminal, it will work.

**Comment by digimezzo** [comment]
@trifon81 I've created a possible fix, but I don't have a Mac to try it out. Could you try out this build and let me know if files play when double-clicking? The build is here: https://github.com/digimezzo/dopamine/releases/tag/v3.0.0-preview.32-mac-double-click-fix

**Comment by trifon81** [comment]
> I've created a possible fix, but I don't have a Mac to try it out. Could you try out this build and let me know if files play when double-clicking? The build is here:

No improvement, same thing.

**Comment by digimezzo** [comment]
Too bad. Thanks for trying it out. I'll keep looking for a fix.

**Comment by trifon81** [comment]
If you need to send it again, I'll try it.

**Comment by digimezzo** [comment]
> If you need to send it again, I'll try it.

Thanks! I got my hands on a virtual mac test machine. That should hopefully make debugging and testing easier. I'm preparing to release Preview 33 today. Then for Preview 34, the mac port will get full attention. This issue will be handled in preview 34.
