### ISSUE TITLE
application crash when playing recently added songs

### ISSUE THREAD

**Issue by Christopolis** [digimezzo/dopamine#658]
every time i click on the album i want to play of a particular artist it crashes, but if i click on the individual files it works fine
here is the log file.

[Dopamine.log](https://github.com/user-attachments/files/16681117/Dopamine.log)

**Comment by digimezzo** [comment]
@Christopolis What is the name of the album? I'm trying to match it to the error message from the log. Thank you.

**Comment by Christopolis** [comment]
Holst: The Planets is what i set it as

**Comment by digimezzo** [comment]
@Christopolis Could you attach you Dopamine.db file to this issue?

**Comment by Christopolis** [comment]
https://mega.nz/file/B4BxHbLK#VmFKmR54RxQm1i4c5IjG0yF0UZr4AhH5lAE4k1ZmVrY

**Comment by digimezzo** [comment]
@Christopolis There seems to be a character in the album artist name that Dopamine has trouble with. Would you mind sending one of some the mp3 files of that album so I can have a look? Thank you.

**Comment by Christopolis** [comment]
that's weird considering the album aritst is blank. the files are  .wav but heres a link. this is a cd i ripped myself with eac and added all the metadata via mp3tag

https://mega.nz/folder/Y1RGWbrJ#7lvblFW9wcsyVLRF6pyRcQ

**Comment by digimezzo** [comment]
Thank you for the files. The album artist is indeed blank. Dopamine seems to have problems reading empty album artists. Other empty tags do not seem to be a problem. Empty album artists in mp3's are fine too. It might be limited to wav. I'm investigating this further.

**Comment by digimezzo** [comment]
@Christopolis I found the bug! It will be fixed in the next preview. You'll have to re-index your collection though. That means, remove your music folder from the collection, let Dopamine remove all songs from the player. Then re-adding you music folder to the collection and let Dopamine perform its indexing. That will solve you problem. The next preview should be ready in a few days.
