### ISSUE TITLE
da-dk locale and new macOS icon missing?

### ISSUE THREAD

**Issue by VisualisationExpo** [digimezzo/dopamine#663]
Hi,

How come that the da-dk locale isn't present in Dopamine anymore despite me spending time updating all the new strings and sharing over on Neowin?

And the icon I made never made it to the macOS version either. I hope I haven't stepped on your toes somewhere or somehow.

I understand not using the app icon, but the translation?

**Comment by digimezzo** [comment]
Hi @VisualisationExpo,

You didn't step on any toes. The fault is all mine. I don't understand what happened. The only explanation I can find it that I have been misorganized and I forgot about it. There are no excuses for this and even less for the fact that I can't find the files on my computer. I am so so sorry about this. I would really love to integrate your work, the icon as well as the translation file. The icon is gorgeous by the way. Dopamine's current mac icon looks out of place and has the wrong size. So if you still have those files available, would you mind adding them to this issue? I'll create a new preview including them as soon as I have them.

Thank you for your work and also for contacting me here. And again, my sincere apologies. This shouldn't have happened.

**Comment by digimezzo** [comment]
@VisualisationExpo I'm afraid I lost your files (My backup before a reformat and PC upgrade was not thorough enough). If you're still up for it and if you still have the files, could you share them again please? If not, I'll understand and no hard feelings. This message is not meant to rush you. I justed wanted to be transparant about why upcoming preview 33 still doesn't include your work. Thanks.

**Comment by VisualisationExpo** [comment]
> @VisualisationExpo I'm afraid I lost your files (My backup before a reformat and PC upgrade was not thorough enough). If you're still up for it and if you still have the files, could you share them again please? If not, I'll understand and no hard feelings. This message is not meant to rush you. I justed wanted to be transparant about why upcoming preview 33 still doesn't include your work. Thanks.

Hi!

I will of course share them again. Thank you for replying 👍🏻 

There are no hard feelings - it's what happens :)

**Comment by VisualisationExpo** [comment]
[DopamineDK.zip](https://github.com/user-attachments/files/16990553/DopamineDK.zip)

Found the files. had to do some digging.. honestly the translation might even be further outdated since some of the previous releases. I'll go have a look after the fact.

@digimezzo

**Comment by digimezzo** [comment]
@VisualisationExpo Thanks a lot! I'm adding these this weekend.

**Comment by digimezzo** [comment]
@VisualisationExpo Looking great! Thanks again! 

![image](https://github.com/user-attachments/assets/02062ae6-3379-4bf1-9d36-5d5225da97f7)

This nightly build has it already: https://github.com/digimezzo/dopamine/actions/runs/10864789536. The public will get it in Preview 34.

**Comment by digimezzo** [comment]
Icon fixed in commit 00dd27d

**Comment by digimezzo** [comment]
@VisualisationExpo I see that the translation is for Dopamine 2. I've created an issue in the dopamine-windows (which hosts Dopamine 2) repository: https://github.com/digimezzo/dopamine-windows/issues/1430

**Comment by digimezzo** [comment]
I'm closing this issue. Icon was added. Translation will be handled in https://github.com/digimezzo/dopamine-windows/issues/1430
