### ISSUE TITLE
The player does not close from the "close" button (MacOS)

### ISSUE THREAD

**Issue by trifon81** [digimezzo/dopamine#674]
Pressing the red hick does nothing but spin endlessly. I show clearly with a clip. This happens from version 31 to version 33.
https://mega.nz/file/gAd3zCYT#Kj0FoQEtUtO0FRfMZWOFWHwKyfG02kgqhFPtS5oW5FE
But there has always been a problem with this button until now. I show the other two problems there were. One was in version 29 and the third one with the popup message is in all the others before that (v14-28).
https://mega.nz/file/1EUCFCKY#ucuRhjuWjchUhbGFjsVUgfasELOTqGES8g6koZ8_X4E
https://mega.nz/file/Ydtj2B5K#ygUHA2-CQ1fLhfoQMLeplYo50MErN00MmcRpS8Egy0Y

**Comment by digimezzo** [comment]
@trifon81 Thanks for the detailed info. I'm planning this for the next preview (preview 34). I finally got a mac test machine, so I can finally give such issues more attention.

**Comment by digimezzo** [comment]
Fixed in 96586ce
