### ISSUE TITLE
Dopamine white-screen on app launch.

### ISSUE THREAD

**Issue by Root1-2** [digimezzo/dopamine#682]
![image](https://github.com/user-attachments/assets/203bbc01-2371-4155-b20f-b87a43a88732)

So, I have been using Dopamine for some time. But suddenly, the app doesn't launch, stuck on white-screen for a long time. After 5-10 min, the dopamine app launch. I have tried uninstalling the app and then reinstalling and it still doesn't work. Only if I reinstall the app by deleting the configuration files/cache, the app launch work properly. Even then after few uses/days, the app stuck on white-screen at launch for 5-10min again.

**Comment by digimezzo** [comment]
@Root1-2 I have a few questions:

- Which version of Dopamine are you using?
- When the white window is visible, could you click on it so that it is active, and then press F12 on your keyboard. That should display the developer pane (see screenshot below). On the developer pane, please select the "Console" tab. Are there errors on the console tab?

![image](https://github.com/user-attachments/assets/cf8e854c-cfc5-4eab-a79c-fe8a644b3d9e)

- Could you start Dopamine from a command prompt? Sometimes it shows extra info when there are errors:

![image](https://github.com/user-attachments/assets/f410e9be-2711-4616-8106-4e9c9c860de7)

**Comment by Root1-2** [comment]
1. I am using the preview 33 version.
2. Console is empty.
![image](https://github.com/user-attachments/assets/f92503f0-a273-4c1e-9fdf-1a5a0abd3698)

3. Ran using cmd. This shows up on the cmd and nothing on the console log either.
![image](https://github.com/user-attachments/assets/6dfd7fda-fa09-4b7f-b827-031d38240c6f)

**Comment by digimezzo** [comment]
@Root1-2 Strange. Must be something in the settings or Dopamine.db that is broken. COudl you zip your Dopamine folder and send it or attach it to this issue?

![image](https://github.com/user-attachments/assets/143e6c5e-357e-42c8-aa85-fd8ad056329d)

**Comment by Root1-2** [comment]
Sure. Here is the zip file:

https://mega.nz/file/m3whwKCI#dIF2QFB75SjwhTTjFlvciOovMX87bZAX9fM_0QlKkQU

**Comment by digimezzo** [comment]
@Root1-2 I tihnk it's a problem with the queue. You have 15000 songs in the queue and Dopamine tries to load metadata for each of these 15000 songs. It takes a lot of times and hangs until it is done. I'm going to try to fix that.

**Comment by Root1-2** [comment]
Yeah sometime I play from the songs section and it automatically add all of the songs in the queue.

**Comment by digimezzo** [comment]
> Yeah sometime I play from the songs section and it automatically add all of the songs in the queue.

That explains it. Good thing you're using it with such a big collection. I don't have that many files to test with. I'll fox the queue. It shouldn't be fetching metadata for files that are already in the database.

**Comment by digimezzo** [comment]
@Root1-2 This nightly build should fix the problem: https://github.com/digimezzo/dopamine/actions/runs/10869139490

**Comment by Root1-2** [comment]
Thank you, good sir. It's working now.

**Comment by digimezzo** [comment]
> Thank you, good sir. It's working now.

You're welcome. Thanks for testing it out. I'm pushing this fix for Preview 34.
