### ISSUE TITLE
Embedded lyrics doesn't add a new line

### ISSUE THREAD

**Issue by Root1-2** [digimezzo/dopamine#687]
![image](https://github.com/user-attachments/assets/ecb08f71-34ba-4632-93c2-91881b5175d3)

So the embedded lyrics doesn't add a new line for songs. I mostly use itunes to add lyrics to my local files. This is a screenshot of the text I embedded. (Left is mediainfo, right is iTunes)

![image](https://github.com/user-attachments/assets/f6259528-468d-4fe6-9841-087ca8b44592)

**Comment by digimezzo** [comment]
@Root1-2 I don't uinderstand what I'm seeing here. Does it mean that Mediainfo also displays the lyrics incorrectly? Could you share one of the files that contains lyrics?

**Comment by digimezzo** [comment]
@Root1-2 I fixed the bug. This build https://github.com/digimezzo/dopamine/actions/runs/10929789657 has the fix and it will be pushed in preview 34.
