### ISSUE TITLE
[Bug] Multi-disc albums displayed incorrectly

### ISSUE THREAD

**Issue by Patrock404** [digimezzo/dopamine#703]
In albums with more than one disc, songs 1 through 9 from both discs are displayed, then 10 through to the end. This also effects the playback order.

Using Version 3 preview 34 on Linux Mint 21.3.

https://github.com/user-attachments/assets/03fad6fb-0d8e-42f5-a4cf-a6e6a34a1c9c

**Comment by digimezzo** [comment]
@Patrock404 Wow that's indeed very wrong :) Could you attach you Dopamine.db file so I can reproduce it here. It would make fixing the bug much easier. Thank you!

**Comment by Patrock404** [comment]
[Dopamine.db.zip](https://github.com/user-attachments/files/17283118/Dopamine.db.zip)

**Comment by digimezzo** [comment]
@Patrock404 Thank you. This build should fix the issue: https://github.com/digimezzo/dopamine/actions/runs/11243047396
Coudl you test it out and let me know?

**Comment by Patrock404** [comment]
Everything looks good on my end, thanks!

**Comment by digimezzo** [comment]
@Patrock404 You're welcome! Thanks for testing it out. I'll release this fix in preview 35.
