### ISSUE TITLE
Artists being lumped together under shorter name.

### ISSUE THREAD

**Issue by yurisuika** [digimezzo/dopamine#704]
This is present in preview 34, I'd have to check if it was so in previous versions but I cannot recall. It seems the trend is if an artist has a name that is part of a word in another artist's name, the other artist's albums will also be displayed under the shorter one.

For example, `Driftwood` is displayed under `Drift`, `blink-182` is displayed under `Link`, `Mid Carson July` is displayed under `July`, `Suicidal Tendencies` is displayed under `Ida`, and god help `Jo` cause everything is displayed under it.

![image](https://github.com/user-attachments/assets/7b959cce-4e5e-4da8-b3f9-82d97317669d)

**Comment by digimezzo** [comment]
@yurisuika This build should fix the issue: https://github.com/digimezzo/dopamine/actions/runs/11249376363
Could you try it out and let me know? Thank you.

**Comment by yurisuika** [comment]
Hi, sorry I did not see this until now.

I don't see any artifacts under 1280, but using 1284 does not seem to offer different results than on preview-34. This included a manual uninstall and data deletion first.

Using the older preview-33 this issue seems to not be present.

**Comment by digimezzo** [comment]
@yurisuika Could you attach your dopamine.db here? I'd like to test this out.

**Comment by digimezzo** [comment]
@yurisuika I see that I missed some cases and added additional fixes. Could you try build 1286?https://github.com/digimezzo/dopamine/actions/runs/11315903549

**Comment by yurisuika** [comment]
[Dopamine.zip](https://github.com/user-attachments/files/17356727/Dopamine.zip)
This is from 1284.

I will test 1286 shortly.

**Comment by yurisuika** [comment]
It seems pretty much resolved in 1286! On some other instances that probably were broken before it seems to work correctly, but I have found one instance where things are not working out quite right. I have an artist named simply `S` on a comp I've never listened to.

In p33, no issue.
![image](https://github.com/user-attachments/assets/54a81341-4732-4ea2-8557-44cc2679e597)

In p34 you can see how that would be quite an issue.
![image](https://github.com/user-attachments/assets/2d1558ef-f079-42f6-b27e-468bdd853f33)

In 1286 it works except for one occasion on which a "feat." artist is involved. I don't have many of these because of the genres I mostly listen to and also in the past retagged stuff to remove featured artists from artist tags and added them as additional album artists.
![image](https://github.com/user-attachments/assets/acface80-be34-4ce4-aa77-59d315453140)

![image](https://github.com/user-attachments/assets/6b559834-faf6-4078-b338-f8276e4de6fd)
You can see that it took the first character after the whitespace following "feat." and counted it as an artist called `S`.

**Comment by digimezzo** [comment]
@yurisuika Buil 1287 Should fix that last problem: https://github.com/digimezzo/dopamine/actions/runs/11317526193

**Comment by yurisuika** [comment]
It does! It takes a while to index my library but yes it is resolved.
