### ISSUE TITLE
[Bug Report] Discord rich presence seems... off..?

### ISSUE THREAD

**Issue by 0error7** [digimezzo/dopamine#710]
Hi there!

I realized since the last 3 or so releases that the discord rich presence seems to be off.
Most of the time it shows up, but then disappear, or it have a huge delay, or shows the previous song and stay locked like that...
I can't really find a temporary fix for that. It seems to refresh when I turn it off and back on from Dopamine's settings, or when I click on next, but then it locks up right after and doesn't seems to update itself when the next song plays.

I can confirm that this bug exist on Windows 10/11 hosts but also on Linux hosts (at least on arch Linux) and that it also appears on fresh installs of Windows/Linux and Dopamine (so not a corrupted installation I think)

I agree this is not a huge bug in itself, but I think that fixing it might be a cool thing! I also agree that discord is a really bugged app and that making things to work properly with it is, most of the time, hard.

Hope you will be able to fix it!

And as always, thank you for providing this amazing app! I love it!

(edit: typos)

**Comment by vtk666** [comment]
Can confirm that with fresh install v3.0.0-preview.35 on Linux Mint 22. 

Fix would be nice! :)

**Comment by vtk666** [comment]
I don´t know what has changed but working again without any problems the last 2-3 days...

**Comment by 0error7** [comment]
Still broken for me.
I tried things like messing with Efficiency mode on Windows 11 24H2 (since it seems to cause so many issues with a lot of apps especially with the 24H2 release)
But nothing
I still have to disable and re-enable the option in the settings everytime a new music plays and sometimes it just froze mid-music and I don't know why

**Comment by 0error7** [comment]
I just reinstalled an old version of Dopamine (3.0.0 preview 25) and the problem still persist
I think it's not something that broke in the new releases, I think it's a problem with discord itself...

**Comment by digimezzo** [comment]
I think I fixed it. I suspect it is a change in behaviour in Discord, a snothign was changed in Dopamine that could have broken it. I think I found a workaround. Preview 37 will be released today for you to test. Keep an eye on the releases page. Thanks for the assistance!

**Comment by 0error7** [comment]
Thanks a lot! I will try that out when the release will be available!

**Comment by 0error7** [comment]
Ok so I've tested the release
just to be sure I've done a clean reinstall of Dopamine, and then a system wide install just to be sure
it seems that the problem persist
this time I've made a video to show the problem.
You can see on the video that the discord rich presence isn't showing up on my profile and then when I turn it off and back on in the settings, it seems to work, but it froze and doesn't refresh when I skip a song...
maybe I'm doing something wrong?

https://github.com/user-attachments/assets/edaa13c7-412d-4fef-8eaa-74bf2851774a

Again, thanks a lot for taking the time for this kind of small bug, this is just awesome from you!
And also, if you don't know or don't want to fix this bug, it's ok ^^

**Comment by digimezzo** [comment]
@0error7 Hi! Is this video made with Preview 37? The behviour that the video shows is exaclty what I get with Preview 36. But it works fine in Preview 37 here. The fix that I applied was essentially clearing the presence before setting a new presence each time the song changes. That is also what toggling discord rich presence in the settings does.

**Comment by 0error7** [comment]
Dopamine 3.0.0 preview 37
![image](https://github.com/user-attachments/assets/c3f70bca-7aad-49a6-b609-307fa05580fb)
I have no idea why this keeps happening for me

**Comment by digimezzo** [comment]
@0error7 Could you send me you log file? You'll find it via this button:

![image](https://github.com/user-attachments/assets/90dd0dab-4e82-4a6e-ad54-53dbd3b1d417)

Thanks!

**Comment by 0error7** [comment]
[Dopamine.log](https://github.com/user-attachments/files/18083599/Dopamine.log)
here

I think I have a solution if that could help you
discord rich presence seems to work fine now but it doesn't refresh when a new song keeps playing
so I think you need to turn off and turn back on the discord rich presence everytime a new song plays, overwise it keep the timer going and keep displaying the previous song

if that could help

**Comment by digimezzo** [comment]
@0error7 Could you try this build? https://github.com/digimezzo/dopamine/actions/runs/12263016557

**Comment by 0error7** [comment]
I'm starting to wonder if my discord client isn't bugged...
it still exhibit the same issue...

I've done a clean install of Dopamine just to be sure and I've indeed installed the new build you've sent me

**Comment by 0error7** [comment]
No way..
I found out why it was doing this...

**Comment by 0error7** [comment]
I've turned off the taskbar icon and now it seems to work perfectly fine

**Comment by digimezzo** [comment]
What do you mean? The tray icon?

**Comment by 0error7** [comment]
yes, I've turned it off and now it works perfectly fine

**Comment by 0error7** [comment]
![image](https://github.com/user-attachments/assets/551f7346-7d4a-427d-a832-ec56b71f8c88)
this setting

**Comment by 0error7** [comment]
Dopamine's one

**Comment by digimezzo** [comment]
That's so weird! I've had it on the whole time here. Could you trye with preview 37 again?

**Comment by 0error7** [comment]
with the default preview 37 (from the release tab) discord rich presence is still broken and I had to turn it off and on several times for it to kick in
and even with the system tray icon disabled, it doesn't seems to work properly

**Comment by 0error7** [comment]
I've tried once again with the build you've sent me and it works perfectly fine as long as the tray icon is turned off

**Comment by 0error7** [comment]
but not with the official preview 37

**Comment by digimezzo** [comment]
Ok. Thanks for all your testing. It's useful info. Although I still don't understand how the tray icon is related to the discord issues. And also don't understand why I don't have the problem here. It would help it I could rperoduce it. I'm not giving up yet though.

**Comment by 0error7** [comment]
Thank you a lot for taking your time on a small issue like this one too!
And yeah, the fact you don't have the same issue is really weird, but at least the build I have with this setting turned off is working flawlessly for me
That's a very good thing!

**Comment by 0error7** [comment]
I have a theory of why the discord tray icon is causing this issue
I'm not really good at creating apps but I know a bit about windows and all of the running process
I thought maybe the tray icon is an instance of Dopamine in itself and discord is maybe  refering to it as being dopamine and maybe the tray icon doesn't update when a new song is playing, causing discord to not refresh the rich presence

**Comment by digimezzo** [comment]
You're welcome! I care about all bugs. But some are more challenging than other. I'm trying one more thing. But it'll only be ready tomorrow or the day after tomorrow. Then I'll need your help again to test it out.

**Comment by 0error7** [comment]
alright!
I will be there to test!
And I will definitively make a donation at this point!

**Comment by digimezzo** [comment]
@0error7 Thank you!

**Comment by digimezzo** [comment]
@0error7 Could you try out this build and let me know if it's better or worse with the tray icon on and off? https://github.com/digimezzo/dopamine/actions/runs/12290456182
Thanks!

**Comment by 0error7** [comment]
I tested it
so far it seems OK!
I just had to turn the discord rich presence off and on again and restart dopamine for it to show up on my profile
maybe this has something to do with vencord needing a restart for an update? idk

but it works! Even with the tray icon now!
Thank you so much!

**Comment by digimezzo** [comment]
@0error7 Thanks for testing it out! No idea why turning off and on was required. Might be that an explicit disconnect from Discord was required to use the new way of connecting.
I'm glad it works. Crossing fingers that it remains that way. I'll prepare a new release that contains that fix.

**Comment by 0error7** [comment]
I have no idea too
at least it works haha

**Comment by 0error7** [comment]
Tested today
Still working perfectly fine! As soon as a song is playing, it shows up on my discord profile without having to touch anything at all!
Thank you so much!!
And I've made a donation for this project :D

**Comment by digimezzo** [comment]
@0error7 Thank you so much for your donation and also for all your testing! You were a tremendous help.
Also, I found out why you needed to turn off and on the option to get it to work. That'll be fixed in the next preview.

**Comment by 0error7** [comment]
That's cool!
And you're welcome!
