### ISSUE TITLE
Is there a Theme Limit?

### ISSUE THREAD

**Issue by Crocodile73** [digimezzo/dopamine#712]
Is there a limit to how many themes you can have in Dopamine?. It looks like you cannot have more than 10 themes. Can this be increased at all?

update:- Oh i cannot add any new theme, even if i delete one i made.

**Comment by digimezzo** [comment]
@Crocodile73 It's not supposed to have a theme limit. Could you attach the log to see if there is an error?

**Comment by Crocodile73** [comment]
[2024-10-21 15:29:51.968] [error] [AppearanceService] [getThemesFromThemesDirectory]  Could not parse theme file. Error: Bad control character in string literal in JSON at position 471

**Comment by digimezzo** [comment]
@Crocodile73 yes that is a mistake in one of your theme files.

**Comment by Crocodile73** [comment]
> @Crocodile73 yes that is a mistake in one of your theme files.


redone the theme, it's identical to the first one. But it works. Very odd. Close this. Sorry for hassle.

**Comment by digimezzo** [comment]
@Crocodile73 That's great news! Don't worry about it. Glad I could help!
