### ISSUE TITLE
[BUG] MacOS Focus Lost After Manually Skipping Songs in Gapless Playback

### ISSUE THREAD

**Issue by fr-eed** [digimezzo/dopamine#715]
When the "Gapless playback" feature is enabled, Dopamine loses media focus after manually skipping a few songs using the "Now Playing" feature in macOS Control Center or multimedia keys. Once Dopamine loses focus, pressing the multimedia keys (play/pause, next/previous) defaults to controlling Apple Music instead of Dopamine.

Steps to Reproduce:

    Enable "Gapless playback" in Dopamine.
    Restart the app.
    Play any song.
    Skip a song using multimedia keys or via the macOS Control Center.
    Unfocus or close the Dopamine main window.
    Skip a song again using multimedia keys or Control Center.
    Observe that media focus is lost, and multimedia keys no longer control Dopamine.
    Press multimedia keys again, and Apple Music takes over media control.

MacOS version: macOS 15.0.1
Dopamine: 3.0.0-preview.36

**Comment by digimezzo** [comment]
@fr-eed Thank you for the bug report. I'll investigate this.

**Comment by fr-eed** [comment]
Also to note. Currently Dopamine works weirdly with the Control Center Now Playing widget, after switching a song it disappears for a moment and then appears

**Comment by digimezzo** [comment]
@fr-eed Does this also happen when gapless playback is disabled?

**Comment by fr-eed** [comment]
> @fr-eed Does this also happen when gapless playback is disabled?

Yes

https://github.com/user-attachments/assets/2541e789-8e7b-4b08-861e-0048bbde4fdb

**Comment by digimezzo** [comment]
@fr-eed Keep an eye in this build: https://github.com/digimezzo/dopamine/actions/runs/11468241556

It's currently building. As soon as it has artifacts, could you try it out? I tried to fix the problem in it. Thanks!

**Comment by fr-eed** [comment]
> @fr-eed Keep an eye in this build: https://github.com/digimezzo/dopamine/actions/runs/11468241556
> 
> It's currently building. As soon as it has artifacts, could you try it out? I tried to fix the problem in it. Thanks!

So, gapless playback doesn't cause initial bug but now:


- After selecting any song/skipping, it starts playing for 200 ms and then restarts from the beginning causing it to repeat a sequence.
- Sometimes previews fail to load in Playing Now widget.


Behavior shown in my video still persists 

Maybe MacOS doesn't need the gapless feature at all?

**Comment by digimezzo** [comment]
@fr-eed Could you try out this build? https://github.com/digimezzo/dopamine/actions/runs/11538007114
Thank you.

**Comment by digimezzo** [comment]
@fr-eed Thanks for testing out. Is it possible to make a video of the 200ms problem? I'm not sure how I should reproduce that. Thanks

**Comment by fr-eed** [comment]
> @fr-eed Thanks for testing out. Is it possible to make a video of the 200ms problem? I'm not sure how I should reproduce that. Thanks

It's an audio issue. I can share a recording later.

After some more testing I've found out that this bug occurs only with wireless headphones. Most likely system wants to sync it with wireless delay and your app overrides it

**Comment by fr-eed** [comment]
https://github.com/user-attachments/assets/a606ab76-4894-436c-8331-b7313a239f48

It sounds like this with gapeless playback on with bluetooth headphones connected as main audio output.

Tested on this build: https://github.com/digimezzo/dopamine/actions/runs/11619031390
