### ISSUE TITLE
Windows media overlay disappears after a few seconds

### ISSUE THREAD

**Issue by probablyjassin** [digimezzo/dopamine#726]
When a new song starts playing (not by resuming), the Windows media overlay appears as intended.

However, there is an issue where after about 10 seconds, this disappears, and Windows no longer knows which song is being played.

I noticed this because Wallpaper Engine displays the cover art for a few moments, but then looses it.

I'm sure this is an issue with the Music Player, not with Windows or Wallpaper Engine, because for example Spotify immediately shows the Windows media overlay as soon as it's opened.

Meanwhile this music player only shows it once for a few moments after a song started playing.

**Comment by Galexion** [comment]
Can confirm this happening on Windows & Arch Linux, Having the same issues with XSOverlay and Cosmic Desktop Environment, this is definitely a Player issue.

This can also happen when trying to skip Multiple Songs at a time.

**Comment by digimezzo** [comment]
@probablyjassin @Galexion This is currently being looked at and will be fixed in preview 36.
