### ISSUE TITLE
after last file has been plaid not localized text is displayed

### ISSUE THREAD

**Issue by BodoTh** [digimezzo/dopamine#729]
When the last file has been played and Dopamine stops there is a screen in English when German is activated. The buttons say:
Nothing is playing
Play all
Shuffle all

**Comment by digimezzo** [comment]
@BodoTh Hi! That's because the German translation is incomplete. That's the current state of the translation: https://github.com/digimezzo/dopamine/blob/master/src/assets/i18n/de.json

if you're up for it, you're help with this would be very welcome :)

**Comment by digimezzo** [comment]
@BodoTh Thanks a lot! I'll add your translation for the next preview. I'm closing this ticket now.
