### ISSUE TITLE
At the beginning of each track playback stutters and repeats for a split second

### ISSUE THREAD

**Issue by bryanparadis** [digimezzo/dopamine#731]
### Description
0.5s in it stutters and then repeats a bit but continues playing properly afterwards. Happens every time a track is played. Cannot reproduce with other players.

### Example:
[bad](https://drive.google.com/file/d/18aUpXIF4OXzRRXKVA72dRnBiUYvq2rf1/view?usp=drive_link)
[good](https://drive.google.com/file/d/18_lZchsNbz6P6VntiMLjskdH8WaNOEfm/view?usp=drive_link)

### Log:
[Dopamine.log](https://github.com/user-attachments/files/17891655/Dopamine.log)

**Comment by BodoTh** [comment]
I have the same issue. This only happens at the beginning of an audio file. When starting playback in the middle of a file this does not seem to happen.

**Comment by digimezzo** [comment]
@bryanparadis @BodoTh That should be fixed in preview 36. Will be released today.

**Comment by digimezzo** [comment]
Fixed in 9a53f80

**Comment by bryanparadis** [comment]
> Fixed in [9a53f80](https://github.com/digimezzo/dopamine/commit/9a53f804ab46c7b0cf7fb0255cbeb14e94ee3434)

Freshly reproduced in 35, installed 36 and can confirm that the issue is solved.
