### ISSUE TITLE
Columns option on Songs screen is hard to find

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine#75]
In Dopamine 2, the "Columns..." option on the songs screen is hard to find. Can we improve this for Dopamine 3?

Some ideas:

Option 1: a right click on the column headers could allow column editing
Option 2: a more visible button to edit columns

**Comment by Cyberdroid1** [comment]
Option 1 would be preferable as an extra button could look cluttered.

**Comment by digimezzo** [comment]
Fixed in b35f0eefb1c5698005e1a934582752c2389b6373
