### ISSUE TITLE
Make a Windows version

### ISSUE THREAD

**Issue by VFDan** [digimezzo/dopamine#78]
It's annoying to have to build with npm and node, why can't a simple exe just be released? I do love the music player, but having to download and install a whole bunch of other things turns me away from Dopamine 3, I just use version 2.

**Comment by digimezzo** [comment]
@VFDan Patience. Dopamine 3 will be released for Windows and Linux. There are no builds yet, because the player is in early development. It doesn't display any song and cannot play anything yet. So there is no need to download and build it currently. Dopamine 2 is the only released version.

**Comment by VFDan** [comment]
Oh okay, I thought it was ready, sorry.
