### ISSUE TITLE
Add option to follow system theme (dark/light mode)

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine#79]
This will probably require an upgrade of electron.

**Comment by digimezzo** [comment]
This feature was added in bf258d2f3cf0c00ec678675f0b321e1a196f563e

**Comment by Mennaruuk** [comment]
Hey @digimezzo do you know where I can find this option in the Windows version? This is what I see:

![image](https://user-images.githubusercontent.com/52135169/158730951-5b3897fc-9edf-40dc-9f9d-8ab2c0caeef4.png)
