### ISSUE TITLE
[Question] Is the database structure staying the same

### ISSUE THREAD

**Issue by SCLeoX** [digimezzo/dopamine#8]
I have been a long time Dopamine user (the windows version). If I understand correctly, this electron version will become the future of Dopamine. I have rated hundreds of songs with the rating functionality with the windows version of Dopamine, and I don't want to lose those data. Thus, I am asking, will the database structure for the electron version stay the same as the windows version? If not, will there be any conversion tool?

Thanks.

**Comment by digimezzo** [comment]
@SCLeoX The database structure will change. But I will provide a way to export rating and love data from version 2.0.x and import it in version 3.0.

**Comment by SCLeoX** [comment]
@digimezzo I am so glad to hear that. <3
