### ISSUE TITLE
Maybe it's better to use Observable instead of Promise?

### ISSUE THREAD

**Issue by Magentaize** [digimezzo/dopamine#89]
For Angular, rxjs is its core dependency, so using Observable looks like more natural and modern, and can obtain the power of stream api through rxjs.

**Comment by digimezzo** [comment]
@Magentaize It depends in which context. Promises are a handy tool when calling async functions. I like using promises in async/await operations, to keep the code-flow linear. The syntax is very comparable to C# in that case.
I use observables when raising events. The code-base of Dopamine does not have observables yet, but they are coming, when the services get more functionality. Examples of the use of observable can be found in Knowte. For example: https://github.com/digimezzo/knowte/blob/master/src/app/services/collection/collection.service.ts

**Comment by Magentaize** [comment]
I see,  just noticed that observables are converted to promises in dialog.service.ts, so...I'm a little curious about the reason why.  But since the linear control flow is your habit, it's ok. For me, I'm a fan of functional programming :)

**Comment by digimezzo** [comment]
Indeed, I convert observables to promises to avoid function chaining, nesting and subscriptions which I must remember to unsubscribe. I prefer linear control flow :) The conversion to promises is just about the linearity. I find that it also makes unit testing easier (but that might be related to my lack of experience with functional programming). One exception is when I need to raise events. Then observables are really handy.

**Comment by digimezzo** [comment]
I'm further reading on this, and I stumbled upon this article: https://indepth.dev/posts/1287/rxjs-heads-up-topromise-is-being-deprecated: toPromise() will be deprecated starting from  RxJs 7. I'll have be be careful with such conversions.

**Comment by Magentaize** [comment]
Yep, for testing observables, some reactive unit test libraries are needed. In fact, observable is contagious, just like that await in turning from sync api to async api. Using observable means maybe there's no "await" function calls and almost all functions accept an observable argument and return an observable.
